#!/usr/bin/env /usr/local/bin/python3.12
"""
mann_whitney_table_hppd_binary.py
==================================
Table of Mann-Whitney U test statistics for hppd_binary (PPA History),
grouped by IV type (SP Use Patterns / VCH Task Behavior / HGF Estimates).

Mimics the single-panel-a style of regression_results_table.py exactly:
  - ax.table() renderer with Arial font
  - Bold-italic section-header rows with top+bottom structural lines only
  - No per-row borders on data rows; thick bottom line closes the table
  - Right-divider on Predictor column throughout
  - No amber highlighting; data cells are unbolded plain text

Columns
  Predictor | PPA(−) Mdn [Q1, Q3] | PPA(+) Mdn [Q1, Q3] | U | r_rb | p
            | p_FDR+ | p_FDR- | N
  where r_rb, p_FDR+ and p_FDR- use mathtext for the subscript notation and are
  re-rendered as true Word subscripts in the .docx. The FDR headers are bold
  upright to match the plain "p"/"U"/"N" headers; r_rb stays italic, which is
  the standard notation for a rank-biserial correlation.

  p_FDR+  Benjamini-Hochberg across all 9 frequentist tests for hppd_binary.
  p_FDR-  Benjamini-Hochberg within the predictor's own iv_type_dict block
          only (m = 3): sp_predictors, vch_behavior, or vch_computations.

  Both come from fdr_correction.py via `family_frame("hppd_binary")` — this
  script never runs BH itself, so the two supplement tables cannot drift onto
  different family definitions or a different FDR method.

Data sources
  results/hppd_binary/{ivtype}/data_visualization/summary_results/boxplot_grid.csv
  for ivtype in [sp_predictors, vch_behavior, vch_computations]
  Generated by 0X_all_figures.py from df_sp_plot (SP users only, n ≈ 186).
  One row per predictor, test = mann_whitney.
  The FDR columns re-read the same CSVs through fdr_correction.py, so the
  uncorrected p in this table and the p the correction was computed from are
  by construction the same number.

Output
  results/supplement/tables/supplementary_table_s2.png
  results/supplement/tables/supplementary_table_s2.csv
  results/supplement/tables/supplementary_table_s2.docx

Usage
  cd 04_visualizations
  /usr/local/bin/python3.12 supplement/mann_whitney_table_hppd_binary.py
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

_HERE = Path(__file__).resolve().parent
os.chdir(_HERE)
sys.path.insert(0, str(_HERE.parent.parent / "modules"))

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from master_config import iv_type_dict, iv_type_group_labels, dv_to_lab_short

# FDR corrections are computed once, in fdr_correction.py, and imported here.
from fdr_correction import family_frame, FDR_PLUS_COL, FDR_MINUS_COL

# ── CONFIG ───────────────────────────────────────────────────────────────────

RESULTS_BASE = Path("../../results")
HPPD_DIR     = RESULTS_BASE / "hppd_binary"
OUTPUT_DIR   = RESULTS_BASE / "supplement" / "tables"
OUTPUT_FILE  = OUTPUT_DIR / "supplementary_table_s2.png"
OUTPUT_CSV   = OUTPUT_DIR / "supplementary_table_s2.csv"
OUTPUT_DOCX  = OUTPUT_DIR / "supplementary_table_s2.docx"

IVTYPES    = ["sp_predictors", "vch_behavior", "vch_computations"]
OUTPUT_DPI = 400

FONT_FAMILY = "Arial"
C_WHITE     = "#FFFFFF"

# Column headers. r_rb / p_FDR+ / p_FDR- are mathtext so the PNG renders an
# italic letter with a roman subscript; the same strings are the keys of
# SUBSCRIPT_MAP below, which re-renders them as real subscripts in Word.
P_FDR_PLUS_HDR  = r"$\mathbf{p}_{\mathbf{FDR}+}$"   # BH over all 9 frequentist tests
P_FDR_MINUS_HDR = r"$\mathbf{p}_{\mathbf{FDR}-}$"   # BH within the iv_type block (m=3)

MWU_COLS = [
    "PPA(\u2212) Mdn [Q1, Q3]",   # PPA(−) Mdn [Q1, Q3]
    "PPA(+) Mdn [Q1, Q3]",
    "U",
    r"$r_{rb}$",                   # rank-biserial correlation
    "p",
    P_FDR_PLUS_HDR,
    P_FDR_MINUS_HDR,
    "N",
]

# Rich-text segments for the .docx. Keys must match the mathtext headers above.
SUBSCRIPT_MAP = {
    r"$r_{rb}$": [
        {"text": "r",  "italic": True},
        {"text": "rb", "italic": True, "subscript": True},
    ],
    P_FDR_PLUS_HDR: [
        {"text": "p"},
        {"text": "FDR+", "subscript": True},
    ],
    P_FDR_MINUS_HDR: [
        {"text": "p"},
        {"text": "FDR\u2212", "subscript": True},
    ],
}

# ── FORMATTING HELPERS ───────────────────────────────────────────────────────

def _strip(s: str) -> str:
    """Strip trailing zeros after decimal point; remove the point if no decimals remain.
    Preserves leading sign characters ('+' / '-').
    Examples: '19.000' → '19', '22.500' → '22.5', '0.042' → '0.042'
    """
    if "." not in s:
        return s
    s = s.rstrip("0").rstrip(".")
    return s


def fmt_num(v: float) -> str:
    """Format a plain number to at most 3 decimal places, stripping trailing zeros."""
    return _strip(f"{v:.3f}")


def fmt_mdn_iqr(med: float, q1: float, q3: float) -> str:
    """Format as 'X [Q1, Q3]' with trailing zeros stripped; em-dash on missing data."""
    if any(pd.isna(v) for v in (med, q1, q3)):
        return "\u2014"
    return f"{fmt_num(med)} [{fmt_num(q1)}, {fmt_num(q3)}]"


def fmt_u(v: float) -> str:
    """Format U statistic, stripping trailing '.0' for whole-number values."""
    if pd.isna(v):
        return "\u2014"
    return _strip(f"{v:.1f}")


def fmt_r(v: float) -> str:
    """Format rank-biserial r with explicit sign, stripping trailing zeros."""
    if pd.isna(v):
        return "\u2014"
    return _strip(f"{v:+.3f}")


def fmt_p(v: float) -> str:
    """Format p-value; use '< .001' for very small values."""
    if pd.isna(v):
        return "\u2014"
    if v < 0.001:
        return "< .001"
    return f"{v:.3f}"


# ── DATA LOADING ─────────────────────────────────────────────────────────────

def load_mwu_data() -> dict[str, pd.DataFrame]:
    """Load boxplot_grid.csv for each IVTYPE. Raises FileNotFoundError if absent."""
    dfs: dict[str, pd.DataFrame] = {}
    for ivtype in IVTYPES:
        csv_path = (
            HPPD_DIR / ivtype / "data_visualization"
            / "summary_results" / "boxplot_grid.csv"
        )
        if not csv_path.exists():
            raise FileNotFoundError(
                f"Expected summary CSV not found: {csv_path}\n"
                "Re-run 0X_all_figures.py (RUN_HPPD_CAPS_FIGS=True) to generate it."
            )
        dfs[ivtype] = pd.read_csv(csv_path)
    return dfs


def load_fdr_lookup() -> pd.DataFrame:
    """Per-predictor FDR-adjusted p-values for the hppd_binary family.

    Returns the 9 Mann-Whitney rows of `family_frame("hppd_binary")`, indexed by
    predictor variable name.
    """
    fam = family_frame("hppd_binary")
    expected = sum(len(iv_type_dict[ivt]) for ivt in IVTYPES)
    if len(fam) != expected:
        raise ValueError(
            f"Expected {expected} Mann-Whitney rows from fdr_correction; got {len(fam)}."
        )
    return fam.set_index("predictor")


def get_stats(df: pd.DataFrame, var: str) -> dict:
    """Extract MWU stats for one predictor variable from a loaded CSV."""
    row = df[df["dv"] == var]
    if len(row) == 0:
        nan = float("nan")
        return {k: nan for k in [
            "statistic", "p_value", "rank_biserial_correlation",
            "group_1_median", "group_1_iqr_q1", "group_1_iqr_q3",
            "group_2_median", "group_2_iqr_q1", "group_2_iqr_q3",
            "sample_size",
        ]}
    r = row.iloc[0]
    return {
        "statistic":                 r["statistic"],
        "p_value":                   r["p_value"],
        "rank_biserial_correlation": r["rank_biserial_correlation"],
        "group_1_median":            r["group_1_median"],
        "group_1_iqr_q1":            r["group_1_iqr_q1"],
        "group_1_iqr_q3":            r["group_1_iqr_q3"],
        "group_2_median":            r["group_2_median"],
        "group_2_iqr_q1":            r["group_2_iqr_q1"],
        "group_2_iqr_q3":            r["group_2_iqr_q3"],
        "sample_size":               r["sample_size"],
    }


# ── ROW BUILDER ──────────────────────────────────────────────────────────────

def build_rows(mwu_data: dict[str, pd.DataFrame], fdr: pd.DataFrame) -> list[dict]:
    """Build the flat row list: alternating group_header and data dicts."""
    rows: list[dict] = []
    for ivtype in IVTYPES:
        df = mwu_data[ivtype]
        rows.append({"type": "group_header", "label": iv_type_group_labels[ivtype]})
        for var in iv_type_dict[ivtype]:
            s = get_stats(df, var)
            cells = [
                fmt_mdn_iqr(s["group_1_median"], s["group_1_iqr_q1"], s["group_1_iqr_q3"]),
                fmt_mdn_iqr(s["group_2_median"], s["group_2_iqr_q1"], s["group_2_iqr_q3"]),
                fmt_u(s["statistic"]),
                fmt_r(s["rank_biserial_correlation"]),
                fmt_p(s["p_value"]),
                fmt_p(fdr.loc[var, FDR_PLUS_COL]),
                fmt_p(fdr.loc[var, FDR_MINUS_COL]),
                str(int(s["sample_size"])) if not pd.isna(s["sample_size"]) else "\u2014",
            ]
            rows.append({
                "type":  "data",
                "label": dv_to_lab_short.get(var, var),
                "cells": cells,
            })
    return rows


# ── ROWS → DISPLAY DATAFRAME ─────────────────────────────────────────────────

def rows_to_display(rows: list[dict]) -> tuple[pd.DataFrame, pd.DataFrame]:
    """Convert row-dict list → (display_df, row_meta)."""
    col_headers = ["Predictor"] + MWU_COLS
    n_data = len(MWU_COLS)

    display_rows: list[list] = []
    meta_rows:    list[dict] = []

    for row in rows:
        if row["type"] == "group_header":
            display_rows.append([row["label"]] + [""] * n_data)
            meta_rows.append({"row_type": "section_header"})
        else:
            display_rows.append([row["label"]] + row["cells"])
            meta_rows.append({"row_type": "data"})

    display_df = pd.DataFrame(display_rows, columns=col_headers)
    row_meta   = pd.DataFrame(meta_rows)
    return display_df, row_meta


# ── PANEL RENDERER ────────────────────────────────────────────────────────────

def draw_panel(
    ax: plt.Axes,
    display_df: pd.DataFrame,
    row_meta: pd.DataFrame,
) -> None:
    """Render the MWU table on ax, exactly mimicking regression_results_table.py.

    Style (mirrors _save_png_table_thickonly / draw_panel in that script):
      - Header row:        bold, visible_edges="TBR" (pred) / "TB" (data), lw=1.5
      - Section headers:   bold+italic, visible_edges="TBR"/"TB", lw=1.0
      - Data rows:         no borders except right-divider on pred col (lw=0.7)
      - Last data row:     thick bottom border (lw=1.5) on all cells
      - No highlighting;   data cell text is unbolded
    """
    ax.axis("off")
    plt.rcParams["font.family"] = FONT_FAMILY

    n_rows = len(display_df)
    n_cols = len(display_df.columns)   # 9: Predictor + 8 data cols

    # ── column widths (fractions of axis width; must sum to 1.0) ─────────────
    # Predictor col: 0.19  (fits ~24-char label e.g. "Age at First Use (Years)")
    # Each Mdn col:  0.18  (fits "0.042 [0.014, 0.068]" ≈ 23 chars)
    # U:             0.08
    # r_rb:          0.075
    # p:             0.075
    # p_FDR+:        0.08
    # p_FDR-:        0.08
    # N:             0.06
    # Total: 0.19 + 0.18 + 0.18 + 0.08 + 0.075 + 0.075 + 0.08 + 0.08 + 0.06 = 1.00
    _col_widths = [0.19, 0.18, 0.18, 0.08, 0.075, 0.075, 0.08, 0.08, 0.06]

    # ── row-height allocation (identical logic to regression_results_table_v2) ─
    HEADER_W  = 1.4
    SECTION_W = 1.3
    DATA_W    = 1.0
    total_w   = HEADER_W + sum(
        SECTION_W if row_meta.iloc[i]["row_type"] == "section_header" else DATA_W
        for i in range(n_rows)
    )
    per       = 0.96 / total_w
    header_h  = HEADER_W  * per
    section_h = SECTION_W * per
    data_h    = DATA_W    * per

    # ── build table ──────────────────────────────────────────────────────────
    table = ax.table(
        cellText=display_df.values,
        colLabels=display_df.columns.tolist(),
        loc="upper left",
        cellLoc="center",
        colLoc="center",
    )
    table.auto_set_font_size(False)
    table.set_fontsize(9.5)

    # ── style each cell ──────────────────────────────────────────────────────
    for (row_i, col_i), cell in table.get_celld().items():
        cell.set_facecolor(C_WHITE)
        cell.set_edgecolor("#222222")
        cell.set_width(_col_widths[col_i])
        cell.PAD = 0.05

        # ─── column header row ───
        if row_i == 0:
            cell.visible_edges = "TBR" if col_i == 0 else "TB"
            cell.set_linewidth(1.5)
            cell.set_height(header_h)
            if col_i == 0:
                cell.set_text_props(weight="bold", ha="left", va="center")
            else:
                cell.set_text_props(weight="bold", ha="center", va="center")
            continue

        # ─── data / section rows ───
        row_type = row_meta.iloc[row_i - 1]["row_type"]
        is_last  = (row_i == n_rows)

        if row_type == "section_header":
            cell.set_height(section_h)
            cell.visible_edges = "TBR" if col_i == 0 else "TB"
            cell.set_linewidth(1.0)
            if col_i == 0:
                cell.set_text_props(
                    style="italic", weight="bold", ha="left", va="center"
                )
            else:
                cell.set_text_props(ha="center", va="center")

        else:
            cell.set_height(data_h)
            if col_i == 0:
                # Thin right divider throughout; thick bottom on last row only
                cell.visible_edges = "BR" if is_last else "R"
                cell.set_linewidth(1.5 if is_last else 0.7)
                cell.set_text_props(ha="left", va="center")
            else:
                # No borders on interior data cells; thick bottom on last row only
                cell.visible_edges = "B" if is_last else ""
                cell.set_linewidth(1.5 if is_last else 0.4)
                cell.set_text_props(ha="center", va="center")


# ── MAIN ─────────────────────────────────────────────────────────────────────

def build_csv_data(mwu_data: dict[str, pd.DataFrame], fdr: pd.DataFrame) -> pd.DataFrame:
    """Build a structured CSV with raw numeric values for Mann-Whitney U results.

    Column names match the PNG table headers. The PNG merges Mdn/Q1/Q3 into
    a single "Mdn [Q1, Q3]" column; the CSV splits them for editability.
    """
    records: list[dict] = []
    for ivtype in IVTYPES:
        df = mwu_data[ivtype]
        for var in iv_type_dict[ivtype]:
            s = get_stats(df, var)
            records.append({
                "Section": iv_type_group_labels[ivtype],
                "Predictor": dv_to_lab_short.get(var, var),
                "Predictor Variable": var,
                "PPA(\u2212) Mdn": s["group_1_median"],
                "PPA(\u2212) Q1": s["group_1_iqr_q1"],
                "PPA(\u2212) Q3": s["group_1_iqr_q3"],
                "PPA(+) Mdn": s["group_2_median"],
                "PPA(+) Q1": s["group_2_iqr_q1"],
                "PPA(+) Q3": s["group_2_iqr_q3"],
                "U": s["statistic"],
                "r_rb": s["rank_biserial_correlation"],
                "p": s["p_value"],
                "p_FDR+": fdr.loc[var, FDR_PLUS_COL],
                "p_FDR-": fdr.loc[var, FDR_MINUS_COL],
                "N": int(s["sample_size"]) if not pd.isna(s["sample_size"]) else np.nan,
            })
    return pd.DataFrame(records)


def main() -> None:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    print("Loading Mann-Whitney U data …")
    mwu_data = load_mwu_data()

    print("Loading FDR corrections from fdr_correction.py …")
    fdr = load_fdr_lookup()

    print("Building rows …")
    rows           = build_rows(mwu_data, fdr)
    display_df, meta = rows_to_display(rows)

    # ── save CSV (UTF-8 BOM for Excel/Google Sheets compatibility) ───────────
    csv_df = build_csv_data(mwu_data, fdr)
    csv_df.to_csv(OUTPUT_CSV, index=False, encoding="utf-8-sig")
    print(f"Saved CSV → {OUTPUT_CSV}")

    # ── save Word table (primary submission artifact) ─────────────────────────
    # r_{rb}, p_FDR+ and p_FDR- all need subscript rendering in Word
    from _docx_helper import save_docx_tables
    save_docx_tables(
        panels=[{"display_df": display_df, "row_meta": meta}],
        output_path=OUTPUT_DOCX,
        subscript_map=SUBSCRIPT_MAP,
    )
    print(f"Saved DOCX → {OUTPUT_DOCX}")

    # ── figure sizing ─────────────────────────────────────────────────────────
    n_groups = len(IVTYPES)                                  # 3 section headers
    n_preds  = sum(len(iv_type_dict[ivt]) for ivt in IVTYPES)  # 9 predictors

    # Row heights in inches: col header ≈ 0.38, section header ≈ 0.30, data ≈ 0.25
    panel_h = 0.38 + n_groups * 0.30 + n_preds * 0.25

    # Width: Mdn [Q1,Q3] cols need ~23 chars each.  Predictor col ~24 chars.
    # At 9.5pt, ~7–8 chars/in.  Adding the two FDR columns dropped mdn_frac
    # from 0.21 to 0.18, so fig_w has to grow to keep each Mdn col ≥ 3 in.
    # axes_w = fig_w * 0.97  →  fig_w ≥ 3 / (0.18 * 0.97) ≈ 17.2; use 17.5.
    fig_w = 17.5

    print(f"Figure: {fig_w:.1f} × {panel_h:.1f} in")
    fig = plt.figure(figsize=(fig_w, panel_h))
    ax  = fig.add_axes([0.03, 0.0, 0.97, 1.0])
    draw_panel(ax, display_df, meta)

    print(f"Saving → {OUTPUT_FILE}")
    fig.savefig(OUTPUT_FILE, dpi=OUTPUT_DPI, bbox_inches="tight")
    plt.close(fig)
    print("Done.")


if __name__ == "__main__":
    main()
