#!/usr/bin/env /usr/local/bin/python3.12
"""
spearman_table_caps_vision.py
=============================
Single-panel publication table of Spearman correlations between `caps_vision`
(CAPS visual items endorsed) and every forest-plot predictor, grouped by IV type
(SP Use Patterns / VCH Task Behavior / HGF Estimates).

Companion to `mann_whitney_table_hppd_binary.py`, which does the same for the
`hppd_binary` outcome. The two share renderer style, formatting helpers, column
conventions and FDR source — keep them parallel.

Columns
  Predictor | ρ | p | p_FDR+ | p_FDR- | N
  where p_FDR+ and p_FDR- use mathtext for the subscript notation in the PNG and
  are re-rendered as true Word subscripts in the .docx. Their p is bold upright,
  matching the plain "p" and "N" headers.

  p_FDR+  Benjamini-Hochberg across all 9 frequentist tests for caps_vision.
  p_FDR-  Benjamini-Hochberg within the predictor's own iv_type_dict block
          only (m = 3): sp_predictors, vch_behavior, or vch_computations.

Correlation type by block
  The three `sp_predictors` rows are **partial** Spearman correlations
  controlling for `age_v2`, read from `correlation_grid_age_control.csv`. The
  six VCH rows are zero-order Spearman correlations from `correlation_grid.csv`,
  because no age-controlled variant is generated for those blocks. This mirrors
  the manuscript: Fig. 1b shows the age-controlled panel and
  `05_results_narrative/results_narrative.py` quotes the age-controlled values.
  The table legend states which rows are which; the sidecar `.csv` also carries
  a `Correlation Type` column per row. The block mapping itself lives in
  `CAPS_GRID_BY_IVTYPE` in `fdr_correction.py`, not in this file.

Data sources
  Everything — ρ, p, N, and both FDR columns — comes from
  `fdr_correction.family_frame("caps_vision")`, so this script never reads a
  results CSV or runs BH itself. That function reads:
    results/caps_vision/sp_predictors/data_visualization/summary_results/
        correlation_grid_age_control.csv
    results/caps_vision/{vch_behavior,vch_computations}/data_visualization/
        summary_results/correlation_grid.csv
  both generated by 0X_all_figures.py.

Output
  results/supplement/tables/supplementary_table_s6.png
  results/supplement/tables/supplementary_table_s6.csv
  results/supplement/tables/supplementary_table_s6.docx

Usage
  cd 04_visualizations
  /usr/local/bin/python3.12 supplement/spearman_table_caps_vision.py
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

_HERE = Path(__file__).resolve().parent
os.chdir(_HERE)
sys.path.insert(0, str(_HERE.parent.parent / "modules"))

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

from master_config import iv_type_dict, iv_type_group_labels, dv_to_lab_short

# FDR corrections (and the underlying Spearman values) are computed once, in
# fdr_correction.py, and imported here.
from fdr_correction import family_frame, FDR_PLUS_COL, FDR_MINUS_COL

# ── CONFIG ───────────────────────────────────────────────────────────────────

RESULTS_BASE = Path("../../results")
OUTPUT_DIR   = RESULTS_BASE / "supplement" / "tables"
OUTPUT_FILE  = OUTPUT_DIR / "supplementary_table_s6.png"
OUTPUT_CSV   = OUTPUT_DIR / "supplementary_table_s6.csv"
OUTPUT_DOCX  = OUTPUT_DIR / "supplementary_table_s6.docx"

IVTYPES    = ["sp_predictors", "vch_behavior", "vch_computations"]
OUTPUT_DPI = 400

FONT_FAMILY = "Arial"
C_WHITE     = "#FFFFFF"

# Column headers. ρ is the literal Greek character (Arial renders it, and the
# other supplement tables already use ν / β / ω in labels). The two FDR headers
# are mathtext so the PNG gets an italic p with a roman subscript; the same
# strings key SUBSCRIPT_MAP for the Word rendering.
RHO_HDR         = "ρ"
P_FDR_PLUS_HDR  = r"$\mathbf{p}_{\mathbf{FDR}+}$"   # BH over all 9 frequentist tests
P_FDR_MINUS_HDR = r"$\mathbf{p}_{\mathbf{FDR}-}$"   # BH within the iv_type block (m=3)

SPEARMAN_COLS = [
    RHO_HDR,
    "p",
    P_FDR_PLUS_HDR,
    P_FDR_MINUS_HDR,
    "N",
]

# Rich-text segments for the .docx. Keys must match the headers above.
SUBSCRIPT_MAP = {
    RHO_HDR: [
        {"text": "ρ", "italic": True},
    ],
    P_FDR_PLUS_HDR: [
        {"text": "p"},
        {"text": "FDR+", "subscript": True},
    ],
    P_FDR_MINUS_HDR: [
        {"text": "p"},
        {"text": "FDR−", "subscript": True},
    ],
}


# ── FORMATTING HELPERS ───────────────────────────────────────────────────────
# Kept byte-identical to mann_whitney_table_hppd_binary.py so the two tables
# format the same numbers the same way.

def _strip(s: str) -> str:
    """Strip trailing zeros after decimal point; remove the point if no decimals
    remain. Preserves leading sign characters ('+' / '-')."""
    if "." not in s:
        return s
    s = s.rstrip("0").rstrip(".")
    return s


def fmt_rho(v: float) -> str:
    """Format Spearman rho with explicit sign, stripping trailing zeros."""
    if pd.isna(v):
        return "—"
    return _strip(f"{v:+.3f}")


def fmt_p(v: float) -> str:
    """Format a p-value; use '< .001' for very small values."""
    if pd.isna(v):
        return "—"
    if v < 0.001:
        return "< .001"
    return f"{v:.3f}"


# ── DATA LOADING ─────────────────────────────────────────────────────────────

def load_spearman() -> pd.DataFrame:
    """The 9 Spearman rows of the caps_vision family, indexed by predictor."""
    fam = family_frame("caps_vision")
    expected = sum(len(iv_type_dict[ivt]) for ivt in IVTYPES)
    if len(fam) != expected:
        raise ValueError(
            f"Expected {expected} Spearman rows from fdr_correction; got {len(fam)}."
        )
    return fam.set_index("predictor")


# ── ROW BUILDER ──────────────────────────────────────────────────────────────

def build_rows(spear: pd.DataFrame) -> list[dict]:
    """Build the flat row list: alternating group_header and data dicts."""
    rows: list[dict] = []
    for ivtype in IVTYPES:
        rows.append({"type": "group_header", "label": iv_type_group_labels[ivtype]})
        for var in iv_type_dict[ivtype]:
            r = spear.loc[var]
            cells = [
                fmt_rho(r["effect"]),
                fmt_p(r["p_raw"]),
                fmt_p(r[FDR_PLUS_COL]),
                fmt_p(r[FDR_MINUS_COL]),
                str(int(r["n"])) if not pd.isna(r["n"]) else "—",
            ]
            rows.append({
                "type":  "data",
                "label": dv_to_lab_short.get(var, var),
                "cells": cells,
            })
    return rows


# ── ROWS → DISPLAY DATAFRAME ─────────────────────────────────────────────────

def rows_to_display(rows: list[dict]) -> tuple[pd.DataFrame, pd.DataFrame]:
    """Convert row-dict list → (display_df, row_meta)."""
    col_headers = ["Predictor"] + SPEARMAN_COLS
    n_data = len(SPEARMAN_COLS)

    display_rows: list[list] = []
    meta_rows:    list[dict] = []

    for row in rows:
        if row["type"] == "group_header":
            display_rows.append([row["label"]] + [""] * n_data)
            meta_rows.append({"row_type": "section_header"})
        else:
            display_rows.append([row["label"]] + row["cells"])
            meta_rows.append({"row_type": "data"})

    display_df = pd.DataFrame(display_rows, columns=col_headers)
    row_meta   = pd.DataFrame(meta_rows)
    return display_df, row_meta


# ── PANEL RENDERER ────────────────────────────────────────────────────────────

def draw_panel(
    ax: plt.Axes,
    display_df: pd.DataFrame,
    row_meta: pd.DataFrame,
) -> None:
    """Render the Spearman table on ax.

    Style is copied from mann_whitney_table_hppd_binary.draw_panel:
      - Header row:        bold, visible_edges="TBR" (pred) / "TB" (data), lw=1.5
      - Section headers:   bold+italic, visible_edges="TBR"/"TB", lw=1.0
      - Data rows:         no borders except right-divider on pred col (lw=0.7)
      - Last data row:     thick bottom border (lw=1.5) on all cells
      - No highlighting;   data cell text is unbolded
    """
    ax.axis("off")
    plt.rcParams["font.family"] = FONT_FAMILY

    n_rows = len(display_df)
    n_cols = len(display_df.columns)   # 6: Predictor + 5 data cols

    # ── column widths (fractions of axis width; must sum to 1.0) ─────────────
    # Predictor col: 0.40  (longest label is 37 chars,
    #                       "Contingency Belief Evolution Rate (ω)")
    # Each data col: 0.12  (widest content is "< .001" / "-0.156")
    # Total: 0.40 + 5 × 0.12 = 1.00
    _col_widths = [0.40] + [0.12] * 5

    # ── row-height allocation (same logic as the Mann-Whitney table) ─────────
    HEADER_W  = 1.4
    SECTION_W = 1.3
    DATA_W    = 1.0
    total_w   = HEADER_W + sum(
        SECTION_W if row_meta.iloc[i]["row_type"] == "section_header" else DATA_W
        for i in range(n_rows)
    )
    per       = 0.96 / total_w
    header_h  = HEADER_W  * per
    section_h = SECTION_W * per
    data_h    = DATA_W    * per

    # ── build table ──────────────────────────────────────────────────────────
    table = ax.table(
        cellText=display_df.values,
        colLabels=display_df.columns.tolist(),
        loc="upper left",
        cellLoc="center",
        colLoc="center",
    )
    table.auto_set_font_size(False)
    table.set_fontsize(9.5)

    # ── style each cell ──────────────────────────────────────────────────────
    for (row_i, col_i), cell in table.get_celld().items():
        cell.set_facecolor(C_WHITE)
        cell.set_edgecolor("#222222")
        cell.set_width(_col_widths[col_i])
        cell.PAD = 0.05

        # ─── column header row ───
        if row_i == 0:
            cell.visible_edges = "TBR" if col_i == 0 else "TB"
            cell.set_linewidth(1.5)
            cell.set_height(header_h)
            if col_i == 0:
                cell.set_text_props(weight="bold", ha="left", va="center")
            else:
                cell.set_text_props(weight="bold", ha="center", va="center")
            continue

        # ─── data / section rows ───
        row_type = row_meta.iloc[row_i - 1]["row_type"]
        is_last  = (row_i == n_rows)

        if row_type == "section_header":
            cell.set_height(section_h)
            cell.visible_edges = "TBR" if col_i == 0 else "TB"
            cell.set_linewidth(1.0)
            if col_i == 0:
                cell.set_text_props(
                    style="italic", weight="bold", ha="left", va="center"
                )
            else:
                cell.set_text_props(ha="center", va="center")

        else:
            cell.set_height(data_h)
            if col_i == 0:
                # Thin right divider throughout; thick bottom on last row only
                cell.visible_edges = "BR" if is_last else "R"
                cell.set_linewidth(1.5 if is_last else 0.7)
                cell.set_text_props(ha="left", va="center")
            else:
                # No borders on interior data cells; thick bottom on last row only
                cell.visible_edges = "B" if is_last else ""
                cell.set_linewidth(1.5 if is_last else 0.4)
                cell.set_text_props(ha="center", va="center")


# ── MAIN ─────────────────────────────────────────────────────────────────────

def build_csv_data(spear: pd.DataFrame) -> pd.DataFrame:
    """Structured CSV with raw numeric values, one row per predictor.

    `Correlation Type` records the partial-vs-zero-order distinction that the
    rendered table deliberately omits.
    """
    records: list[dict] = []
    for ivtype in IVTYPES:
        for var in iv_type_dict[ivtype]:
            r = spear.loc[var]
            records.append({
                "Section": iv_type_group_labels[ivtype],
                "Predictor": dv_to_lab_short.get(var, var),
                "Predictor Variable": var,
                "Correlation Type": r["test_detail"],
                "rho": r["effect"],
                "p": r["p_raw"],
                "p_FDR+": r[FDR_PLUS_COL],
                "p_FDR-": r[FDR_MINUS_COL],
                "N": int(r["n"]) if not pd.isna(r["n"]) else np.nan,
            })
    return pd.DataFrame(records)


def main() -> None:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    print("Loading Spearman data + FDR corrections from fdr_correction.py …")
    spear = load_spearman()

    print("Building rows …")
    rows             = build_rows(spear)
    display_df, meta = rows_to_display(rows)

    # ── save CSV (UTF-8 BOM for Excel/Google Sheets compatibility) ───────────
    csv_df = build_csv_data(spear)
    csv_df.to_csv(OUTPUT_CSV, index=False, encoding="utf-8-sig")
    print(f"Saved CSV → {OUTPUT_CSV}")

    # ── save Word table (primary submission artifact) ─────────────────────────
    from _docx_helper import save_docx_tables
    save_docx_tables(
        panels=[{"display_df": display_df, "row_meta": meta}],
        output_path=OUTPUT_DOCX,
        subscript_map=SUBSCRIPT_MAP,
    )
    print(f"Saved DOCX → {OUTPUT_DOCX}")

    # ── figure sizing ─────────────────────────────────────────────────────────
    n_groups = len(IVTYPES)                                    # 3 section headers
    n_preds  = sum(len(iv_type_dict[ivt]) for ivt in IVTYPES)  # 9 predictors

    # Row heights in inches: col header ≈ 0.38, section header ≈ 0.30, data ≈ 0.25
    panel_h = 0.38 + n_groups * 0.30 + n_preds * 0.25

    # Width: predictor col needs ~37 chars at 9.5pt (~7–8 chars/in) ≈ 4.7 in.
    # axes_w = fig_w * 0.97, pred_frac = 0.40  →  fig_w ≥ 4.7 / (0.40 * 0.97) ≈ 12.1.
    # 11.0 is used instead: it leaves the single longest label (vch_omega) to
    # overhang slightly, exactly as it already does in the Mann-Whitney table,
    # and keeps the PNG a sane width. The .docx autofits and wraps properly.
    fig_w = 11.0

    print(f"Figure: {fig_w:.1f} × {panel_h:.1f} in")
    fig = plt.figure(figsize=(fig_w, panel_h))
    ax  = fig.add_axes([0.03, 0.0, 0.97, 1.0])
    draw_panel(ax, display_df, meta)

    print(f"Saving → {OUTPUT_FILE}")
    fig.savefig(OUTPUT_FILE, dpi=OUTPUT_DPI, bbox_inches="tight")
    plt.close(fig)
    print("Done.")


if __name__ == "__main__":
    main()
