####################################################################################################################################################################
####################################################################################################################################################################
######################## Script for running multivariate BRMS models for 2 underlying distribution types (gaussian and binomial) ###################################
################################################ Built for parallelization in job array on HPC #####################################################################
### To run: job lines are generated by 03_hpc/generate_hpc_jobs.py, which writes
### the SLURM array file and copies this script into the job bundle. ###########
######## Drop the job array .txt on mccleary in directory wiht the dataframes and the different model type directories (eg. gaussian_hierarchicial) ################
########################   module load dSQ; dsq --job-file ***.TXT NAME HERE*** --mem-per-cpu 4g -t ***MINUTES PER TASK***:00 --mail-type ALL########################
# spvar = focal predictor (eg. vch_bl_yes_75)
# cov = string denoting covariates type for sensitivity analyses (nice_covariates_spusers = main)
####################################################################################################################################################################
####################################################################################################################################################################

# Use a version-specific personal library so cluster/R upgrades do not break package lookup.
r_minor <- sub("\\..*$", "", R.version$minor)
user_r_lib <- path.expand(file.path("~", "R", paste0(R.version$major, ".", r_minor)))
if (!dir.exists(user_r_lib)) {
  dir.create(user_r_lib, recursive = TRUE, showWarnings = FALSE)
}
.libPaths(c(user_r_lib, .libPaths()))

args = commandArgs(trailingOnly = TRUE) # Get all the arguments left in terminal after calling the script
print("Script called!")
library(tidyverse)
library(brms)
library(glue)
library(tidyr)
library(zoo)
library(bayesplot)
library(rstan)
library(posterior)
library(bayestestR)   # compute_hdi_94() wraps bayestestR::hdi()

library(DHARMa)
library(DHARMa.helpers) # to install need to install.packages("remotes") and then remotes::install_github("Pakillo/DHARMa.helpers")

# distributions3 is deliberately NOT attached: it masks brms::Beta with
# distributions3::Beta(alpha, beta), which would make get_brms_family("beta")
# return a distributions3 object instead of a brms family.  Load it namespaced
# (distributions3::) if you ever need it.

### set BMRS constants
seed = 5124
# warmup = 6000 and adapt_delta = 0.98 (set below) are deliberately generous:
# some caps_vision models produce divergent transitions at lighter settings.
# These match hpc_mediation.R so every model in the manuscript is sampled
# identically.
warmup = 6000
chains = 4

# ── A note on the word "counterfactual" ──────────────────────────────────────
# "counterfactual" appears throughout this file's output filenames
# ({dv}_counterfactual.csv) and CSV column names. It is a misnomer: what is
# computed is an average predictive comparison, not a causal counterfactual. The
# name is retained because compile_nonsp_results.py reads those filenames and
# columns. The estimator is specified in full at the APC block below.

# ── 94% Highest Density Interval ───────────────────────────────────────────
# Returns the 94% highest density interval of a posterior as a named pair,
# c(lower = ..., upper = ...).
#
# Thin wrapper over bayestestR::hdi(). It exists for two reasons: callers here
# want a plain named numeric pair rather than the one-row data.frame bayestestR
# returns, and callers want a non-finite draw to be an error rather than
# something quietly dropped.
#
# Fails loudly on non-finite input. Posterior draws should never be NA, NaN, or
# Inf; when they are, it signals an upstream problem with the fit (for example a
# shape parameter collapsing toward 0 in a hurdle model). Dropping those draws
# silently would report an interval computed from a smaller, different posterior
# than the one the model actually produced.
# Condition class carried by every compute_hdi_94() failure. Call sites that wrap
# model steps in tryCatch() re-raise on this class rather than logging and moving
# on, so a bad posterior fails the job instead of silently producing no output.
HDI_ERROR_CLASS <- "hdi_integrity_error"

compute_hdi_94 <- function(samples, cred_mass = 0.94) {
  if (!is.numeric(samples)) {
    stop(errorCondition(
      paste0("compute_hdi_94(): expected a numeric vector, got ",
             paste(class(samples), collapse = "/"), "."),
      class = HDI_ERROR_CLASS))
  }

  n_bad <- sum(!is.finite(samples))
  if (n_bad > 0L) {
    stop(errorCondition(sprintf(
      paste0("compute_hdi_94(): %d of %d draws are NA/NaN/Inf. Posterior draws ",
             "should always be finite, so this signals an upstream problem with ",
             "the fit. Investigate the model rather than filtering the draws."),
      n_bad, length(samples)), class = HDI_ERROR_CLASS))
  }

  if (length(samples) < 2L) {
    stop(errorCondition(sprintf(
      "compute_hdi_94(): need at least 2 draws to form an interval, got %d.",
      length(samples)), class = HDI_ERROR_CLASS))
  }

  h <- bayestestR::hdi(samples, ci = cred_mass)

  # bayestestR warns and returns NA when ceiling(ci * n) >= n. That is a real
  # failure for our purposes, so promote it to an error.
  if (!is.finite(h$CI_low) || !is.finite(h$CI_high)) {
    stop(errorCondition(sprintf(
      paste0("compute_hdi_94(): bayestestR::hdi() returned a non-finite interval for ",
             "n = %d draws at ci = %s. The sample is too short for the requested ",
             "credible mass."),
      length(samples), format(cred_mass)), class = HDI_ERROR_CLASS))
  }

  c(lower = h$CI_low, upper = h$CI_high)
}

# ── Average predictive comparison ─────────────────────────────────────────────
# average_predictive_comparison(): returns the S-vector of population-average
# contrasts  E[Y | spvar = x1, Z_i] - E[Y | spvar = x0, Z_i],  one value per
# posterior draw.
#
# Set the focal predictor to a counterfactual value for every observed unit, hold
# that unit's own covariates at their observed values, predict on the RESPONSE
# scale, and average the differences.  This is the "average comparison" of
# Arel-Bundock, Greifer & Heiss (2024), *How to Interpret Statistical Models
# Using marginaleffects for R and Python*, JSS 111(9), 1-32,
# doi:10.18637/jss.v111.i09.
#
#     for each posterior draw s (S of them):
#       for each subject i (N of them):  E[Y | x0, Z_i]  and  E[Y | x1, Z_i]
#       average the difference over the N subjects   -> one delta for draw s
#     -> S values of delta
#
#   N (inner)  averages over the COVARIATE distribution, which is what makes the
#              effect population-average rather than specific to one profile.
#   S (outer)  carries PARAMETER uncertainty.  Never averaged over; it is what
#              becomes the HDI.
#
# WHY posterior_epred() RATHER THAN A HAND-BUILT LINEAR PREDICTOR
#   posterior_epred() returns draws of E[Y] already on the response scale, using
#   this family's own mean function -- for hurdle_negbinomial that is
#   mu / (1 - (shape/(mu+shape))^shape) * (1 - hu), i.e. both submodels and the
#   zero-truncation renormalisation; for bernoulli it is plogis(eta).  See
#   ?posterior_epred.brmsfit.  For what separates epred from posterior_linpred()
#   and posterior_predict(), and when each is the right one, see Andrew Heiss,
#   "Visualizing the differences between Bayesian posterior predictions, linear
#   predictions, and the expectation of posterior predictions" (2022):
#   https://www.andrewheiss.com/blog/2022/09/26/guide-visualizing-types-posteriors/#tldr-diagrams-and-cheat-sheets
#
#   Assembling eta by hand instead means re-deriving every family's mean function
#   AND matching every term type brms supports.  Until 2026-08-23 this script did
#   exactly that, and scored monotonic mo() covariates as ZERO for every subject:
#   it searched the draws for a column named "b_mo(<var>)", while brms names them
#   "bsp_mo<var>" and "simo_mo<var>1[j]".  The prefix match simply returned
#   nothing and no error was raised.  On a real caps_vision fit that halved the
#   APC.  posterior_epred() cannot drift from the fitted model in this way,
#   because it *is* the fitted model.
#
# ARGUMENTS
#   fit     a fitted brmsfit (single-response; this script fits no mv models)
#   spvar   focal predictor column name, verbatim as it appears in fit$data
#   x0, x1  the two focal values in Gelman-normalised units.  Gelman divides by
#           2 SD, so the default x1 - x0 = 0.5 is exactly +1 raw SD.
#
# RETURNS   numeric vector of length S (one delta per posterior draw)
average_predictive_comparison <- function(fit, spvar, x0 = 0.0, x1 = 0.5) {
  ## fit$data is the model frame brms actually fitted, AFTER complete.cases()
  ## dropped incomplete rows.  Using it rather than the original dataframe is
  ## what makes N the ESTIMATION sample size.
  newdata_x0 <- fit$data
  newdata_x1 <- fit$data

  if (!spvar %in% names(newdata_x0)) {
    stop("average_predictive_comparison(): focal predictor '", spvar,
         "' is not a column of fit$data.  Columns present: ",
         paste(names(newdata_x0), collapse = ", "))
  }

  ## Only the focal predictor moves.  Every covariate keeps its observed value in
  ## BOTH frames -- nothing is set to a mean, a mode, or a reference profile.
  newdata_x0[[spvar]] <- x0
  newdata_x1[[spvar]] <- x1

  ## S x N draws of E[Y] on the RESPONSE scale, one row per posterior draw.
  expected_y_x0 <- posterior_epred(fit, newdata = newdata_x0)
  expected_y_x1 <- posterior_epred(fit, newdata = newdata_x1)

  ## rowMeans() averages over SUBJECTS (columns), leaving one delta per draw.
  rowMeans(expected_y_x1 - expected_y_x0)
}

### ACTUAL MAIN FUNCTION FOR FITTING AND APC ESTIMATION
# adapt_delta: OPTIONAL 10th CLI argument, default 0.98 (the project-wide
# value).  Added 2026-08-31 so a single model can be re-fitted at a tighter
# step-size adaptation without changing it for every model in the pipeline.
# Every existing 9-argument job line therefore behaves exactly as before.
# Raise it when a fit is blocked by a small number of divergent transitions and
# nothing else -- the convergence gate allows zero, and a funnel-prone geometry
# (e.g. hurdle_negbinom_huvary on a thin covariate set) can produce one or two
# even when Rhat and ESS are excellent.
brms_master <- function (settings, dataframe, dv=NA, iter=4000, sp_and_covs, covs, spvar, factororno, adapt_delta=0.98) {

  # ── Path helper ──────────────────────────────────────────────────────────────
  # When spvar is provided: nest results under {spvar}/{covs}/
  # When spvar is "" (covariate-only mode): save directly under {covs}/
  base_dir <- if (nchar(spvar) > 0) file.path(spvar, covs) else covs

  # Parse covariate names from formula RHS — used for per-covariate diagnostics
  all_covariates <- trimws(strsplit(sp_and_covs, "\\+")[[1]])

  # ── Factor handling: only relevant when focal predictor = factor ───────────
  if (nchar(spvar) > 0 && factororno == "factor") {
    print("She's a FACTOR!")
    dataframe[[spvar]] <- as.factor(dataframe[[spvar]])
  }

  # Initialize hu submodel formula string; only set for hurdle families with varying hu.
  # The model_formula construction below checks this to include the second bf() formula.
  hu_formula_str <- NULL

  # Define the formula string, family, and link function from `settings`.
  # Only the five families this pipeline actually uses are supported. Anything
  # else is a configuration error and stops here, rather than failing later with
  # an obscure "object 'formula_str' not found".
  if (settings == "student_t"){
    formula_str <- paste0(dv," ~ ",sp_and_covs)
    fam_to_use = student(link = "identity")
    dataframe <- dataframe[complete.cases(dataframe[[dv]]), ]
  } else if (settings == "logistic" || settings == "bernoulli"){
    # "bernoulli" is the canonical string emitted by generate_hpc_jobs.py for
    # binary (0/1) DVs; "logistic" is an older alias. Both select the same family.
    formula_str <- paste0(dv," ~ ",sp_and_covs)
    fam_to_use = bernoulli(link="logit")
    dataframe <- dataframe[complete.cases(dataframe[[dv]]), ]
  } else if (settings == "zero_inflated_beta"){
    formula_str <- paste0(dv," ~ ",sp_and_covs)
    fam_to_use = zero_inflated_beta()
    dataframe <- dataframe[complete.cases(dataframe[[dv]]), ]
  } else if (settings == "gamma"){
    formula_str <- paste0(dv," ~ ",sp_and_covs)
    fam_to_use = Gamma(link = "log")
    dataframe <- dataframe[complete.cases(dataframe[[dv]]), ]
  } else if (settings == "beta"){
    # Beta() for proportion DVs bounded strictly inside (0,1) — currently only
    # vch_bl_yes_75 (hit rate at 75% contrast; observed range 0.389-0.9999).
    # The RAW column is fitted here, not vch_bl_yes_75_normalized: Beta requires
    # (0,1) and the Gelman-normalized column is negative for most subjects.
    # No rescaling is applied; the DV is already a proportion.
    formula_str <- paste0(dv," ~ ",sp_and_covs)
    fam_to_use = Beta()
    dataframe <- dataframe[complete.cases(dataframe[[dv]]), ]
  } else if (settings == "hurdle_negbinom_huvary") {
    # hurdle_negbinomial() with a varying hu submodel.
    # The hu submodel uses the SAME RHS as the mu (count) submodel, so the predictor
    # (and all covariates) affect BOTH the probability of any nonzero response (hu)
    # AND the expected count given a nonzero response (mu).
    formula_str    <- paste0(dv, " ~ ", sp_and_covs)
    hu_formula_str <- paste0("hu ~ ", sp_and_covs)
    fam_to_use     <- hurdle_negbinomial()
    dataframe      <- dataframe[complete.cases(dataframe[[dv]]), ]
  } else {
    stop(sprintf(
      paste0("Unsupported settings value '%s' for DV '%s'. Supported: student_t, ",
             "logistic/bernoulli, zero_inflated_beta, beta, gamma, hurdle_negbinom_huvary. ",
             "Check VARIABLE_REGISTRY['distribution'] in master_config.py."),
      settings, dv), call. = FALSE)
  }

  # Build brms formula object. For hurdle families with varying hu, include the second
  # distributional-parameter formula. For all others, use a single formula.
  if (!is.null(hu_formula_str)) {
    model_formula <- bf(as.formula(formula_str), as.formula(hu_formula_str))
  } else {
    model_formula <- bf(as.formula(formula_str))
  }

  ### Fit the model
  # Shape prior: inv_gamma(0.4, 0.3), the brms >= 2.22 default for negbinomial
  # families.  Set explicitly so the fit does not depend on the brms version
  # installed -- the older gamma(0.01, 0.01) default allows shape near zero,
  # which fails to converge for caps_vision.
  shape_prior <- if (settings == "hurdle_negbinom_huvary") {
    prior(inv_gamma(0.4, 0.3), class = shape)
  } else {
    NULL
  }
  fit1 <- brm(model_formula,
              data = dataframe,
              family = fam_to_use,
              prior = shape_prior,
              seed = seed,
              warmup = warmup,
              iter = iter,
              chains = chains,
              cores = 4,
              control = list(adapt_delta = adapt_delta, max_treedepth = 12)) 
  # Define relative paths
  fit_dir            <- file.path("results", "fits")
  convergence_dir    <- file.path("convergence_tests")
  pp_dir             <- file.path("pp_checks")
  summary_dir        <- file.path("results", "summary_dfs")
  posterior_draws_dir <- file.path("results", "posterior_draws")
  diagnostic_dir     <- file.path("results", "diagnostics")

  # Create directories using base_dir
  dir.create(file.path(base_dir, fit_dir),             recursive = TRUE, showWarnings = FALSE)
  dir.create(file.path(base_dir, convergence_dir),     recursive = TRUE, showWarnings = FALSE)
  dir.create(file.path(base_dir, pp_dir),              recursive = TRUE, showWarnings = FALSE)
  dir.create(file.path(base_dir, summary_dir),         recursive = TRUE, showWarnings = FALSE)
  dir.create(file.path(base_dir, posterior_draws_dir), recursive = TRUE, showWarnings = FALSE)
  dir.create(file.path(base_dir, diagnostic_dir),      recursive = TRUE, showWarnings = FALSE)

  print("saving posterior draws dataframe...")
  draws <- as_draws_df(fit1)
  write_csv(draws, file.path(base_dir, posterior_draws_dir, paste0(dv, "_draws.csv")))

  print("saving the fit...")
  save(fit1, file = file.path(base_dir, fit_dir, paste0(dv,"_fit.RData")))

  # ── Convergence gate ─────────────────────────────────────────────────────────
  # Decides whether this model's SUMMARY RESULT TABLES may be written:
  #   results/summary_dfs/{dv}.csv  and  results/summary_dfs/{dv}_counterfactual.csv
  # Nothing else is withheld — the fit above, the diagnostics CSV and every
  # diagnostic plot are written either way, so a blocked model still leaves a
  # complete record of why it was blocked.  Thresholds and rationale live in
  # convergence_gate.R.
  #
  # Focal parameters only: b_{spvar}, plus b_hu_{spvar} when the hu submodel
  # carries the predictors.  A covariate-only run (spvar == "") names none, which
  # leaves the Rhat/ESS half vacuous; the divergence check still applies.
  convergence_gate <- check_convergence_gate(
    fit1,
    gate_parameters_nonsp(spvar, has_hu = (settings == "hurdle_negbinom_huvary"))
  )
  report_convergence_gate(convergence_gate,
                          label = paste0(dv, " ~ ", sp_and_covs, "  [", settings, "]"),
                          emit  = print)

  print("nabbing summary...")
  summarized <- summary(fit1)

  # ── Convergence traces ───────────────────────────────────────────────────────
  # With a focal spvar: one trace for that predictor (original behavior).
  # Without spvar: one trace file per covariate.
  print("running convergence test...")
  if (nchar(spvar) > 0) {
    convergence_test <- plot(fit1, variable = spvar, regex = TRUE)[[1]]
    ggsave(file.path(base_dir, convergence_dir, paste0(dv,"_convergence_plot.png")),
           convergence_test, width = 10, height = 8, dpi = 800)
  } else {
    print("  Saving per-covariate convergence traces...")
    for (cov in all_covariates) {
      tryCatch({
        # brms strips underscores internally; match against stripped name
        stripped <- gsub("_", "", cov)
        cov_plots <- plot(fit1, variable = stripped, regex = TRUE)
        if (length(cov_plots) > 0) {
          ggsave(
            file.path(base_dir, convergence_dir, paste0(dv, "_", cov, "_convergence.png")),
            cov_plots[[1]], width = 10, height = 8, dpi = 800
          )
        }
      }, error = function(e) {
        print(paste0("  Convergence trace for ", cov, " failed: ", e$message))
      })
    }
  }

  # calculate rhat, check if any are unsatisfactory, and save them.
  print("checking rhat...")
  rhat_combined <- c(summarized$fixed[, "Rhat"], summarized$random$record_id[, "Rhat"])

  if (length(rhat_combined[abs(1 - rhat_combined) > 0.1]) > 0){
    print("UH OH! One of the fixed or random parameters has an rhat more than 0.1 from 1!!!")
  }

  save(rhat_combined, file = file.path(base_dir, convergence_dir, paste0(dv,"_rhat_combined.RData")))

  ##### Results saved
  print("Great! Now we just need to get a results df...")
  result_df <- summarized$fixed

  result_df$var <- rownames(result_df)
  result_df$model <- settings
  result_df$covariates <- covs
  result_df$N <- nobs(fit1)

  # Programmatic divergent-transition count via brms::nuts_params() — more reliable than
  # rstan::get_num_divergent(fit1$fit), which is deprecated in newer rstan and requires
  # dropping to the raw Stan fit layer. nuts_params() works directly on the brms object.
  result_df$num_divergents <- sum(
    brms::nuts_params(fit1)$Parameter == "divergent__" &
    brms::nuts_params(fit1)$Value      == 1
  )

  # Extract all population-level parameter names.
  # Regular fixed effects use a 'b_' prefix; monotonic effects (mo()) use 'bsp_'.
  # Both need identical HDI and posterior-probability treatment.
  fixed_effect_vars <- grep("^b_|^bsp_", variables(fit1), value = TRUE)

  # Extract posterior draws
  draws <- as_draws_df(fit1)

  # Calculate probabilities and 94% HDI for each fixed effect
  results <- map_df(fixed_effect_vars, ~ {
    samples  <- draws[[.x]]
    var_name <- str_remove(.x, "^b_|^bsp_")
    hdi_vals <- compute_hdi_94(samples)
    data.frame(
      var          = var_name,
      prob_below_0 = mean(samples < 0),
      prob_above_0 = mean(samples > 0),
      hdi_lower_94 = hdi_vals[["lower"]],
      hdi_upper_94 = hdi_vals[["upper"]]
    )
  })

  # Merge with result_df
  result_df <- left_join(result_df, results, by = "var")

  # Save results — unless the convergence gate blocked them.
  if (convergence_gate$pass) {
    print("here comes your results!")
    write.csv(result_df, file.path(base_dir, summary_dir, paste0(dv,'.csv')), row.names = FALSE)
  } else {
    print(paste0("[convergence gate] WITHHELD: ",
                 file.path(base_dir, summary_dir, paste0(dv, ".csv"))))
  }

  ### Do a posterior predictive check!
  # All three pp_check calls are wrapped in tryCatch: hurdle_negbinom_huvary can produce
  # NAs in posterior predictions when shape → 0, crashing pp_check. On failure, any stale
  # image from a prior run is deleted so the absence of a file clearly signals the failure.
  print("aaaand PP check...")
  tryCatch({
    posterior_predictive_check <- pp_check(fit1)
    ggsave(file.path(base_dir, pp_dir, paste0(dv,"_posterior_check_plot.png")),
           plot = posterior_predictive_check, width = 10, height = 8, dpi = 800)
  }, error = function(e) {
    print(paste0("WARNING: pp_check (dens_overlay) failed — ", e$message))
    f <- file.path(base_dir, pp_dir, paste0(dv, "_posterior_check_plot.png"))
    if (file.exists(f)) { file.remove(f); print(paste0("  Deleted stale image: ", f)) }
  })

  ##### Almost done!!! Lets calculate some overall model comparison metrics and diagnostics:
  print("OK lets calculate model comparison metrics and diagnostics... ")

  # Initialize diagnostics list
  diagnostics_list <- list()
  diagnostics_list$dv <- dv
  diagnostics_list$model <- settings
  diagnostics_list$covariates <- covs
  diagnostics_list$N <- nobs(fit1)
  diagnostics_list$spvar <- spvar  # "" for covariate-only analyses

  # Create DHARMa residuals object once (we'll use it for multiple tests).
  # integer = TRUE is required for count/binary families so DHARMa applies the
  # correct randomized quantile residual computation. The default (FALSE) treats
  # the response as continuous, producing incorrect QQ plots and p-values for
  # hurdle_negbinom_huvary (caps_vision) and bernoulli (hppd_binary).
  integer_response <- settings %in% c("hurdle_negbinom_huvary", "bernoulli", "logistic")
  print(paste0("DHARMa integer flag: ", integer_response,
               "  (family settings = '", settings, "')"))
  print("Creating DHARMa residuals object...")
  sim_residuals <- NULL
  tryCatch({
    sim_residuals <- dh_check_brms(fit1, integer = integer_response)
    print("DHARMa residuals object created successfully")
  }, error = function(e) {
    print(paste0("Failed to create DHARMa residuals: ", e$message))
  })

  # ── DHARMa heteroscedasticity ────────────────────────────────────────────────
  # With spvar: test against the focal predictor (original behavior).
  # Without spvar: test against each covariate in the model.
  print("Checking heteroscedasticity with DHARMa...")
  if (nchar(spvar) > 0) {
    if (!is.null(sim_residuals)) {
      # Generate spvar vs. residuals plot (visual only — plotResiduals rank-transforms
      # the predictor internally before fitting the quantile regression lines).
      tryCatch({
        png(file.path(base_dir, diagnostic_dir, paste0(dv,"_heteroscedasticity_check.png")),
            width = 10, height = 8, units = "in", res = 800)
        plotResiduals(sim_residuals, fit1$data[[spvar]])
        dev.off()
      }, error = function(e) {
        if (dev.cur() > 1) dev.off()
        print(paste0("DHARMa heteroscedasticity plot failed: ", e$message))
        f <- file.path(base_dir, diagnostic_dir, paste0(dv, "_heteroscedasticity_check.png"))
        if (file.exists(f)) { file.remove(f); print(paste0("  Deleted stale image: ", f)) }
      })
      # Extract per-quantile p-values via testQuantiles() directly with rank-transformed
      # spvar. plotResiduals() rank-transforms internally before calling testQuantiles,
      # so manually replicating that here ensures the CSV p-values match what the figure
      # shows. Same approach as process_and_save_mediation_model_function.R lines 243–246.
      tryCatch({
        spvar_rk <- rank(fit1$data[[spvar]], ties.method = "average") /
                    length(fit1$data[[spvar]])
        hetero_test <- testQuantiles(sim_residuals, predictor = spvar_rk, plot = FALSE)
        # Combined BH-adjusted p + per-quantile (q25/q50/q75) individual pvals.
        # DHARMa colors a quantile line RED when its individual p < 0.05, even if
        # the combined BH-adjusted p is > 0.05. Saving all three makes the CSV
        # reflect exactly what the plot flags visually.
        diagnostics_list$dharma_heteroscedasticity_pval      <- hetero_test$p.value
        diagnostics_list$dharma_heteroscedasticity_q25_pval  <- if (!is.null(hetero_test$pvals)) hetero_test$pvals[1] else NA_real_
        diagnostics_list$dharma_heteroscedasticity_q50_pval  <- if (!is.null(hetero_test$pvals)) hetero_test$pvals[2] else NA_real_
        diagnostics_list$dharma_heteroscedasticity_q75_pval  <- if (!is.null(hetero_test$pvals)) hetero_test$pvals[3] else NA_real_
        print(paste0("DHARMa heteroscedasticity: combined p=", round(hetero_test$p.value, 4),
                     "  q25=", round(diagnostics_list$dharma_heteroscedasticity_q25_pval, 4),
                     "  q50=", round(diagnostics_list$dharma_heteroscedasticity_q50_pval, 4),
                     "  q75=", round(diagnostics_list$dharma_heteroscedasticity_q75_pval, 4)))
        if (any(c(hetero_test$p.value, hetero_test$pvals) < 0.05, na.rm = TRUE)) {
          print("WARNING: Potential heteroscedasticity (combined or per-quantile p < 0.05)!")
        }
      }, error = function(e) {
        print(paste0("DHARMa heteroscedasticity test failed: ", e$message))
        diagnostics_list$dharma_heteroscedasticity_pval     <- NA
        diagnostics_list$dharma_heteroscedasticity_q25_pval <- NA
        diagnostics_list$dharma_heteroscedasticity_q50_pval <- NA
        diagnostics_list$dharma_heteroscedasticity_q75_pval <- NA
      })
    } else {
      diagnostics_list$dharma_heteroscedasticity_pval     <- NA
      diagnostics_list$dharma_heteroscedasticity_q25_pval <- NA
      diagnostics_list$dharma_heteroscedasticity_q50_pval <- NA
      diagnostics_list$dharma_heteroscedasticity_q75_pval <- NA
    }
  } else {
    # Per-covariate heteroscedasticity
    print("  Running per-covariate DHARMa heteroscedasticity tests...")
    for (cov in all_covariates) {
      col_nm <- paste0("dharma_hetero_pval_", cov)
      if (!is.null(sim_residuals)) {
        cov_data <- fit1$data[[cov]]
        if (!is.null(cov_data)) {
          # Generate covariate vs. residuals plot (visual only).
          tryCatch({
            png(file.path(base_dir, diagnostic_dir,
                          paste0(dv, "_", cov, "_heteroscedasticity.png")),
                width = 10, height = 8, units = "in", res = 800)
            plotResiduals(sim_residuals, cov_data)
            dev.off()
          }, error = function(e) {
            if (dev.cur() > 1) dev.off()
            print(paste0("  DHARMa hetero plot for ", cov, " failed: ", e$message))
            f <- file.path(base_dir, diagnostic_dir, paste0(dv, "_", cov, "_heteroscedasticity.png"))
            if (file.exists(f)) { file.remove(f); print(paste0("  Deleted stale image: ", f)) }
          })
          # Extract per-quantile p-values via testQuantiles() with rank-transformed covariate.
          tryCatch({
            cov_rk <- rank(cov_data, ties.method = "average") / length(cov_data)
            hetero_test <- testQuantiles(sim_residuals, predictor = cov_rk, plot = FALSE)
            diagnostics_list[[col_nm]] <- hetero_test$p.value
            diagnostics_list[[paste0("dharma_hetero_q25_pval_", cov)]] <- if (!is.null(hetero_test$pvals)) hetero_test$pvals[1] else NA_real_
            diagnostics_list[[paste0("dharma_hetero_q50_pval_", cov)]] <- if (!is.null(hetero_test$pvals)) hetero_test$pvals[2] else NA_real_
            diagnostics_list[[paste0("dharma_hetero_q75_pval_", cov)]] <- if (!is.null(hetero_test$pvals)) hetero_test$pvals[3] else NA_real_
            print(paste0("  DHARMa hetero (", cov, "): combined p=", round(hetero_test$p.value, 4),
                         "  q25=", round(diagnostics_list[[paste0("dharma_hetero_q25_pval_", cov)]], 4)))
            if (any(c(hetero_test$p.value, hetero_test$pvals) < 0.05, na.rm = TRUE)) {
              print(paste0("  WARNING: Potential heteroscedasticity for ", cov, " (combined or per-quantile p < 0.05)!"))
            }
          }, error = function(e) {
            print(paste0("  DHARMa test for ", cov, " failed: ", e$message))
            diagnostics_list[[col_nm]]                                   <- NA
            diagnostics_list[[paste0("dharma_hetero_q25_pval_", cov)]]  <- NA
            diagnostics_list[[paste0("dharma_hetero_q50_pval_", cov)]]  <- NA
            diagnostics_list[[paste0("dharma_hetero_q75_pval_", cov)]]  <- NA
          })
        } else {
          print(paste0("  Covariate ", cov, " not found in fit1$data — skipping"))
          diagnostics_list[[col_nm]]                                   <- NA
          diagnostics_list[[paste0("dharma_hetero_q25_pval_", cov)]]  <- NA
          diagnostics_list[[paste0("dharma_hetero_q50_pval_", cov)]]  <- NA
          diagnostics_list[[paste0("dharma_hetero_q75_pval_", cov)]]  <- NA
        }
      } else {
        diagnostics_list[[col_nm]]                                   <- NA
        diagnostics_list[[paste0("dharma_hetero_q25_pval_", cov)]]  <- NA
        diagnostics_list[[paste0("dharma_hetero_q50_pval_", cov)]]  <- NA
        diagnostics_list[[paste0("dharma_hetero_q75_pval_", cov)]]  <- NA
      }
    }
  }

  # ── Posterior correlations ───────────────────────────────────────────────────
  # With spvar: flag coefficients with |r| > 0.7 against spvar posterior (original).
  # Without spvar: all pairwise correlations among fixed effects; flag |r| > 0.7 pairs.
  print("Computing posterior correlations with fixed effects...")
  tryCatch({
    draws <- as_draws_df(fit1)
    # Include both regular (b_) and monotonic (bsp_) population-level parameters.
    fixed_names <- grep("^b_|^bsp_", variables(fit1), value = TRUE)

    if (nchar(spvar) > 0) {
      # Original behavior: correlations of spvar with each other coefficient
      spvar_name <- paste0("b_", spvar)
      if (spvar_name %in% fixed_names) {
        other_vars <- setdiff(fixed_names, spvar_name)
        correlated_vars <- c()
        for (var in other_vars) {
          r <- cor(draws[[spvar_name]], draws[[var]], use = "complete.obs")
          if (!is.na(r) && abs(r) > 0.7) {
            var_clean <- gsub("^b_|^bsp_", "", var)
            correlated_vars <- c(correlated_vars, paste0(var_clean, "(", round(r, 2), ")"))
          }
        }
        diagnostics_list$correlated_variables <- if (length(correlated_vars) > 0)
          paste(correlated_vars, collapse = "; ") else ""
      } else {
        diagnostics_list$correlated_variables <- NA
      }

    } else {
      # Pairwise: all pairs of fixed effects posterior draws
      if (length(fixed_names) > 1) {
        correlated_pairs <- c()
        for (i in 1:(length(fixed_names) - 1)) {
          for (j in (i + 1):length(fixed_names)) {
            r <- cor(draws[[fixed_names[i]]], draws[[fixed_names[j]]], use = "complete.obs")
            if (!is.na(r) && abs(r) > 0.7) {
              v1 <- gsub("^b_|^bsp_", "", fixed_names[i])
              v2 <- gsub("^b_|^bsp_", "", fixed_names[j])
              correlated_pairs <- c(correlated_pairs,
                                    paste0(v1, "<->", v2, "(", round(r, 2), ")"))
            }
          }
        }
        diagnostics_list$correlated_pairs <- if (length(correlated_pairs) > 0)
          paste(correlated_pairs, collapse = "; ") else ""
      } else {
        diagnostics_list$correlated_pairs <- NA
      }
    }
  }, error = function(e) {
    print(paste0("Posterior correlations failed: ", e$message))
    if (nchar(spvar) > 0) {
      diagnostics_list$correlated_variables <- NA
    } else {
      diagnostics_list$correlated_pairs <- NA
    }
  })

  # Check distributional assumption with DHARMa
  print("Checking distributional assumption with DHARMa...")
  if (!is.null(sim_residuals)) {
    tryCatch({
      # Create and save comprehensive DHARMa diagnostic plot
      png(file.path(base_dir, diagnostic_dir, paste0(dv,"_dharma_diagnostics.png")),
          width = 10, height = 8, units = "in", res = 800)
      residuals_results <- testResiduals(sim_residuals)
      dev.off()

      # Store test results
      diagnostics_list$dharma_uniformity_pval <- residuals_results$uniformity$p.value
      diagnostics_list$dharma_dispersion_pval <- residuals_results$dispersion$p.value
      diagnostics_list$dharma_outlier_pval <- residuals_results$outliers$p.value

      # KS test (Kolmogorov-Smirnov) - extract from uniformity test
      diagnostics_list$ks_test_pval <- residuals_results$uniformity$p.value
      diagnostics_list$ks_test_statistic <- residuals_results$uniformity$statistic

      print(paste0("DHARMa uniformity test p-value: ", round(residuals_results$uniformity$p.value, 3)))
      print(paste0("DHARMa dispersion test p-value: ", round(residuals_results$dispersion$p.value, 3)))
      print(paste0("KS test p-value: ", round(residuals_results$uniformity$p.value, 3)))

      if (residuals_results$uniformity$p.value < 0.05) {
        print("WARNING: Residuals deviate from expected distribution (uniformity test p < 0.05)!")
      }
      if (residuals_results$dispersion$p.value < 0.05) {
        print("WARNING: Potential over/under-dispersion detected (p < 0.05)!")
      }

    }, error = function(e) {
      print(paste0("DHARMa diagnostics failed: ", e$message))
      diagnostics_list$dharma_uniformity_pval <- NA
      diagnostics_list$dharma_dispersion_pval <- NA
      diagnostics_list$dharma_outlier_pval <- NA
      diagnostics_list$ks_test_pval <- NA
      diagnostics_list$ks_test_statistic <- NA
    })
  } else {
    diagnostics_list$dharma_uniformity_pval <- NA
    diagnostics_list$dharma_dispersion_pval <- NA
    diagnostics_list$dharma_outlier_pval <- NA
    diagnostics_list$ks_test_pval <- NA
    diagnostics_list$ks_test_statistic <- NA
  }

  # testQuantiles against fitted values (global quantile fit test, no predictor)
  print("Running testQuantiles (vs fitted values) with DHARMa...")
  if (!is.null(sim_residuals)) {
    tryCatch({
      # plotResiduals() rank-transforms fitted values before the quantile test;
      # direct testQuantiles() does not. Use plotResiduals for consistency.
      png(file.path(base_dir, diagnostic_dir, paste0(dv,"_quantiles_check.png")),
          width = 10, height = 8, units = "in", res = 800)
      quantiles_test <- plotResiduals(sim_residuals)
      dev.off()
      diagnostics_list$dharma_quantiles_pval      <- quantiles_test$p.value
      diagnostics_list$dharma_quantiles_q25_pval  <- if (!is.null(quantiles_test$pvals)) quantiles_test$pvals[1] else NA_real_
      diagnostics_list$dharma_quantiles_q50_pval  <- if (!is.null(quantiles_test$pvals)) quantiles_test$pvals[2] else NA_real_
      diagnostics_list$dharma_quantiles_q75_pval  <- if (!is.null(quantiles_test$pvals)) quantiles_test$pvals[3] else NA_real_
      print(paste0("DHARMa quantiles: combined p=", round(quantiles_test$p.value, 4),
                   "  q25=", round(diagnostics_list$dharma_quantiles_q25_pval, 4),
                   "  q50=", round(diagnostics_list$dharma_quantiles_q50_pval, 4),
                   "  q75=", round(diagnostics_list$dharma_quantiles_q75_pval, 4)))
      if (any(c(quantiles_test$p.value, quantiles_test$pvals) < 0.05, na.rm = TRUE)) {
        print("WARNING: Significant quantile deviation (combined or per-quantile p < 0.05)!")
      }
    }, error = function(e) {
      print(paste0("DHARMa testQuantiles failed: ", e$message))
      diagnostics_list$dharma_quantiles_pval     <- NA
      diagnostics_list$dharma_quantiles_q25_pval <- NA
      diagnostics_list$dharma_quantiles_q50_pval <- NA
      diagnostics_list$dharma_quantiles_q75_pval <- NA
    })
  } else {
    diagnostics_list$dharma_quantiles_pval     <- NA
    diagnostics_list$dharma_quantiles_q25_pval <- NA
    diagnostics_list$dharma_quantiles_q50_pval <- NA
    diagnostics_list$dharma_quantiles_q75_pval <- NA
  }

  # Create diagnostics dataframe from whatever succeeded
  print("Creating diagnostics dataframe...")
  diagnostics_df <- as.data.frame(diagnostics_list, stringsAsFactors = FALSE)

  # Save diagnostics separately
  write.csv(diagnostics_df,
            file = file.path(base_dir, diagnostic_dir, paste0(dv,'_diagnostics.csv')),
            row.names = FALSE)
  print(paste0("Diagnostics saved for ", dv))
  print(paste0("Diagnostics columns: ", paste(names(diagnostics_df), collapse = ", ")))

  #############################################################################
  #############################################################################
  ##### AVERAGE PREDICTIVE COMPARISON (APC)                               #####
  #############################################################################
  #
  # The estimand, the derivation, and the reason it is computed with
  # posterior_epred() rather than by hand are all documented on
  # average_predictive_comparison() near the top of this file.  Only the parts
  # specific to WRITING THE RESULT are repeated here.
  #
  # WHAT IS CONTRASTED
  #   x_0 = 0.0   the reference level.  0 is the MEAN of spvar, because Gelman
  #               normalisation centres the variable.
  #   x_1 = 0.5   Gelman divides by 2 SD, so the normalised variable has SD 0.5.
  #               0.5 units is therefore simultaneously "+1 raw SD" and "+1 SD of
  #               the normalised variable" -- both readings give the same number.
  #
  # WHAT COMES OUT
  #   The S values of delta are summarised into a single row:
  #     mean          the REPORTED point estimate as of 2026-08-23 -- the same
  #                   summary of the posterior as the `Estimate` column in this
  #                   script's coefficient tables, so both halves of a results row
  #                   summarise the posterior the same way.  See POINT_ESTIMATE_COL
  #                   in modules/master_config.py.
  #     median        retained so the choice of point estimate can be revisited
  #                   without refitting.  NOT the reported value.
  #     94% HDI       narrowest interval containing 94% of the S values.  The
  #                   94% rather than 95% is the project-wide convention.
  #     prob_above_0  proportion of the S deltas above 0 (and below, likewise).
  #                   Posterior probabilities, NOT p-values: neither can be read
  #                   as a false-positive rate.
  #     scale         what delta is denominated in; differs by family and is
  #                   written verbatim into the CSV's `scale` column.
  #
  # ON THE FILENAME.  "counterfactual" is a misnomer, retained only because it is
  # baked into output filenames, CSV column names, and compile_nonsp_results.py.
  # Renaming it would silently break the compiler.  What is computed is an
  # average predictive comparison.
  #
  # OUTPUT
  #   {base_dir}/summary_dfs/{dv}_counterfactual.csv  (one row)
  #   Columns: dv, settings, spvar, X0, X1, contrast_label, scale,
  #            median, mean, hdi_lower_94, hdi_upper_94, prob_above_0,
  #            prob_below_0, N_obs, N_draws
  #############################################################################

  ## CF_SCALE_BY_FAMILY: the `scale` column's value, per family.  This is a label
  ## only -- it documents the units delta is denominated in and is consumed
  ## downstream by compile_nonsp_results.py.  An unlisted family is a hard stop
  ## rather than a blank label, so a new family cannot reach the CSV unlabelled.
  CF_SCALE_BY_FAMILY <- c(
    hurdle_negbinom_huvary = "response_count",     # delta is in COUNTS of dv
    bernoulli              = "probability",        # delta is a RISK DIFFERENCE
    logistic               = "probability",
    student_t              = "response_scale",
    gamma                  = "response_exp_scale",
    zero_inflated_beta     = "proportion_scale",
    beta                   = "proportion_scale"
  )

  ## Guard: an APC needs a focal predictor to move. Covariate-only runs skip it.
  ## The convergence gate is the second guard: an unconverged posterior gives an
  ## unreportable contrast, so it is not computed rather than computed and binned.
  if (nchar(spvar) > 0 && !convergence_gate$pass) {
    print(paste0("[convergence gate] WITHHELD: ",
                 file.path(base_dir, summary_dir, paste0(dv, "_counterfactual.csv"))))
  } else if (nchar(spvar) > 0) {
    print("Running counterfactual analysis (E[Y|X1] - E[Y|X0])...")

    ## The two focal-predictor values being contrasted, in Gelman-normalised units.
    CF_X0 <- 0.0
    CF_X1 <- 0.5

    tryCatch({

      if (!settings %in% names(CF_SCALE_BY_FAMILY)) {
        stop(paste0("Counterfactual: unsupported family '", settings, "'"))
      }
      ## cf_scale: units of delta, recorded in the CSV
      cf_scale <- unname(CF_SCALE_BY_FAMILY[[settings]])

      ## delta_s: length S - the population-average contrast, one per draw.
      ## Every family's mean function, every covariate type (continuous, factor,
      ## monotonic mo()) and both submodels of a hurdle are handled inside
      ## posterior_epred(); see average_predictive_comparison() above.
      delta_s <- average_predictive_comparison(fit1, spvar, CF_X0, CF_X1)

      ## S_cf / N_cf: draws, and subjects retained in the fit (post complete.cases)
      S_cf <- length(delta_s)
      N_cf <- nrow(fit1$data)

      ## hdi_cf: named c(lower, upper) - errors on any non-finite draw
      hdi_cf <- compute_hdi_94(delta_s)

      ## cf_df: exactly one row; schema is consumed by compile_nonsp_results.py
      cf_df  <- data.frame(
        dv             = dv,
        settings       = settings,
        spvar          = spvar,
        X0             = CF_X0,
        X1             = CF_X1,
        contrast_label = paste0(spvar, ": X0=", CF_X0, " -> X1=", CF_X1,
                                " Gelman units (+1 raw SD)"),
        scale          = cf_scale,
        median         = median(delta_s),
        mean           = mean(delta_s),
        hdi_lower_94   = hdi_cf[["lower"]],
        hdi_upper_94   = hdi_cf[["upper"]],
        ## prob_above_0 / prob_below_0 are raw posterior proportions, NOT p-values
        prob_above_0   = mean(delta_s > 0),
        prob_below_0   = mean(delta_s < 0),
        N_obs          = N_cf,
        N_draws        = S_cf,
        stringsAsFactors = FALSE
      )

      cf_path <- file.path(base_dir, summary_dir, paste0(dv, "_counterfactual.csv"))
      write.csv(cf_df, cf_path, row.names = FALSE)
      print(paste0("Counterfactual saved: ", cf_path))
      ## Reported point estimate is the mean (POINT_ESTIMATE_COL in
      ## modules/master_config.py); cf_df still carries both columns.
      print(paste0("  mean delta = ", round(mean(delta_s), 5),
                   "  |  94% HDI [", round(hdi_cf[["lower"]], 5), ", ",
                   round(hdi_cf[["upper"]], 5), "]",
                   "  |  P(>0) = ", round(mean(delta_s > 0), 3)))

    }, error = function(e) {
      # A compute_hdi_94() failure means the posterior itself is bad. Re-raise it so
      # the job fails, instead of logging and exiting 0 with no output written.
      if (inherits(e, HDI_ERROR_CLASS)) stop(e)
      print(paste0("Counterfactual analysis failed: ", e$message))
    })
  }

  return(result_df)
}

########################################################################################################################################################################################################################################################################
########################################################################################
########################################################################################
####### Now call the function, taking the arguments left in terminal!
########################################################################################
########################################################################################

print("Here are the arguments I have:")
for (i in 1:length(args)) {
  print(paste0("beginarg",i," ",args[i]," ","endarg",i))
}

print(paste0("Reading in the dataframe from: ", args[9]))
df_new <- read.csv(args[9])
print("Dataframe read in!")
print(paste0("Rows before subsetting: ", nrow(df_new)))

# -----------------------------------------------------------------------
# Locate this script's directory, then source the three generated/shared R
# files that live beside it in the job bundle.  All are written or copied by
# generate_hpc_jobs.py; none may be edited in place on the cluster.
#
#   gelman_normalization.R   the Gelman 2SD transform + complete-case helper
#   normalization_vars.R     which variables each normalization rule applies to
#                            (auto-generated from modules/master_config.py)
#
# categorical_factor_vars.R and monotonic_covariates_vars.R are sourced further
# down, at the point they are used.
#
# CRITICAL ORDERING (changed 2026-08-22): the master CSV now ships RAW.
# Normalization happens at the END of this preparation block — after the row
# filters below AND after dropping rows incomplete on any model term — so the
# sample the predictors are centred on is exactly the sample brms fits.
# Normalizing earlier (as the Python generator used to) left every subset model
# scaled to a larger sample than the one entering the likelihood.
# -----------------------------------------------------------------------
script_args  <- commandArgs(trailingOnly = FALSE)
script_dir   <- dirname(normalizePath(
  sub("--file=", "", script_args[grep("--file=", script_args)])
))

for (.f in c("gelman_normalization.R", "normalization_vars.R",
             "categorical_factor_vars.R", "convergence_gate.R")) {
  .path <- file.path(script_dir, .f)
  if (!file.exists(.path)) {
    stop(paste0(.f, " not found at: ", .path, "\n",
                "Re-run generate_hpc_jobs.py and re-transfer the job bundle."))
  }
  source(.path)
  print(paste0("Sourced ", .f, " from: ", .path))
}

# -----------------------------------------------------------------------
# Empty string -> NA for CHARACTER factor covariates.  Added 2026-08-31.
#
# read.csv()'s default na.strings is "NA" only, so a blank field in a
# *character* column arrives as "" rather than NA.  For a factor covariate that
# is silently wrong in three compounding ways: the missing group survives
# drop_incomplete_model_rows() (which tests for NA), as.factor() turns "" into a
# real level, and because "" sorts first it becomes the brms REFERENCE level --
# so every other coefficient would be reported relative to the participants who
# did not answer.
#
# Numeric columns are unaffected (read.csv already yields NA for a blank numeric
# field), which is why this went unnoticed until the first character-valued
# factor covariate was added.  As of 2026-08-31 the only character-typed entry
# in binary_factor_vars is monitor_check_operationalized_final, so this loop is
# a verified no-op for every previously fitted model -- but it guards the whole
# class of bug, not just that one column.
# -----------------------------------------------------------------------
.chr_factor_cols <- intersect(binary_factor_vars, names(df_new))
.chr_factor_cols <- .chr_factor_cols[sapply(df_new[.chr_factor_cols], is.character)]
for (.c in .chr_factor_cols) {
  .n_blank <- sum(df_new[[.c]] == "", na.rm = TRUE)
  if (.n_blank > 0) {
    df_new[[.c]][df_new[[.c]] == ""] <- NA
    print(paste0("  [blank->NA] ", .c, ": ", .n_blank,
                   " empty string(s) converted to NA"))
  }
}

# monotonic_covariates_vars.R is warn-and-continue rather than stop, matching the
# behaviour this script has always had: no fitted model currently uses a mo()
# covariate, so an absent file is survivable.  It IS needed before normalization
# (mo() requires raw integers, so its variables must be excluded from rule 3).
mono_vars_file <- file.path(script_dir, "monotonic_covariates_vars.R")
if (file.exists(mono_vars_file)) {
  source(mono_vars_file)
  print(paste0("Sourced monotonic_covariates_vars.R from: ", mono_vars_file))
} else {
  warning(paste0(
    "monotonic_covariates_vars.R not found at: ", mono_vars_file,
    " — re-run generate_hpc_jobs.py to regenerate it."))
  monotonic_covariate_vars <- character(0)
}

# -----------------------------------------------------------------------
# Auto-subset based on keywords in the model-type / covariate-set name.
# The keyword set is defined by R_SIDE_SUFFIXES in modules/master_config.py;
# this block must stay in step with it (and with hpc_mediation.R).
#   "spusers"       -> keep only SP users (psycheduse_yn == "Yes")
#   "nopsychosis"   -> keep only psych_spectrum_v2 == 0
#   "iqr"           -> drop rows outside [Q1 - 1.5*IQR, Q3 + 1.5*IQR] on spvar;
#                      applied only when spvar (args[6]) is non-empty
#   "nocurrenthppd" -> keep only persist_vis_current == 0
#   "nonan_caps"    -> keep only rows with non-missing caps_bl_1
# Keywords combine (e.g. "nice_covariates_spusers_iqr").
# The 7 "confirmed excluded" records are already NaN'd in the master df -- these
# keywords apply ADDITIONAL sensitivity-analysis exclusions on top of that baseline.
# args[2] = covs = the model-type directory string
# args[6] = spvar (predictor column name; "" for covariate-only analyses)
# -----------------------------------------------------------------------
model_type_str <- args[2]

if (grepl("spusers", model_type_str, ignore.case = FALSE)) {
  n_before <- nrow(df_new)
  df_new <- df_new[df_new$psycheduse_yn == "Yes", ]
  print(paste0("  [spusers] SP-users subset applied: ",
               nrow(df_new), " rows (removed ", n_before - nrow(df_new), ")"))
}

if (grepl("nopsychosis", model_type_str, ignore.case = FALSE)) {
  if (!("psych_spectrum_v2" %in% names(df_new))) {
    stop("  [nopsychosis] psych_spectrum_v2 column missing in df_new")
  }
  n_before <- nrow(df_new)
  df_new <- df_new[!is.na(df_new$psych_spectrum_v2) & df_new$psych_spectrum_v2 <1, ]
  print(paste0("  [nopsychosis] No-psychosis subset applied: ",
               nrow(df_new), " rows (removed ", n_before - nrow(df_new), ")"))
}

# "nooutlier" is refused rather than silently ignored.  It dropped rows with |spvar| > 1 in
# Gelman-normalized space (= +-2 raw SD).  That threshold is only meaningful
# against a fixed normalization sample, and there is no longer one at filter
# time: the CSV ships raw and normalization runs after subsetting.  Rather than
# silently redefine which rows it drops, the keyword is refused.  Use "iqr",
# whose 1.5xIQR fence is quantile-based and therefore identical on any positive
# affine rescaling of the column.  Removed from R_SIDE_SUFFIXES in
# master_config.py too, so generation fails first; this stop() is the backstop
# for a stale job file already staged on the cluster.
if (grepl("nooutlier", model_type_str, ignore.case = FALSE)) {
  stop(paste0(
    "  [nooutlier] This keyword is not supported and filters ",
    "anything. It thresholded |spvar| on the Gelman-normalized scale, which has ",
    "no fixed meaning now that normalization happens in R after subsetting. ",
    "Model type requested: '", model_type_str, "'. ",
    "Use 'iqr' instead, or regenerate the job file with generate_hpc_jobs.py."))
}

# The iqr filter requires a focal predictor — skip when spvar is empty.
# spvar arrives as its {x}_normalized name, but that column does not exist yet
# (normalization is below), so resolve to the raw column.  The 1.5xIQR fence is
# quantile-based, so it selects exactly the same rows on either scale.
if (grepl("iqr", model_type_str, ignore.case = FALSE)) {
  spvar_col <- args[6]
  if (nchar(spvar_col) > 0) {
    spvar_col <- resolve_raw_column(df_new, spvar_col)
    n_before  <- nrow(df_new)
    x <- df_new[[spvar_col]]

    if (all(is.na(x))) {
      print(paste0("  [iqr] All values missing for spvar=", spvar_col,
                   "; skipping IQR filter."))
    } else {
      q1 <- as.numeric(stats::quantile(x, probs = 0.25, na.rm = TRUE))
      q3 <- as.numeric(stats::quantile(x, probs = 0.75, na.rm = TRUE))
      iqr_val <- q3 - q1
      lower <- q1 - 1.5 * iqr_val
      upper <- q3 + 1.5 * iqr_val

      df_new <- df_new[!is.na(df_new[[spvar_col]]) &
                       df_new[[spvar_col]] >= lower &
                       df_new[[spvar_col]] <= upper, ]

      print(paste0("  [iqr] IQR exclusion applied (spvar=", spvar_col,
                   ", Q1=", round(q1, 4), ", Q3=", round(q3, 4),
                   ", IQR=", round(iqr_val, 4),
                   ", bounds=[", round(lower, 4), ", ", round(upper, 4), "]): ",
                   nrow(df_new), " rows (removed ", n_before - nrow(df_new), ")"))
    }
  } else {
    print("  [iqr] spvar is empty — IQR filter requires a focal predictor; skipping.")
  }
}

if (grepl("nocurrenthppd", model_type_str, ignore.case = FALSE)) {
  n_before <- nrow(df_new)
  df_new <- df_new[!is.na(df_new$persist_vis_current) & df_new$persist_vis_current == 0, ]
  print(paste0("  [nocurrenthppd] No-current-HPPD subset applied: ",
               nrow(df_new), " rows (removed ", n_before - nrow(df_new), ")"))
}


if (grepl("nonan_caps", model_type_str, ignore.case = FALSE)) {
  n_before <- nrow(df_new)
  if (!("caps_bl_1" %in% names(df_new))) stop("[nonan_caps] caps_bl_1 column missing")
  df_new <- df_new[!is.na(df_new$caps_bl_1), ]
  print(paste0("  [nonan_caps] Non-NaN caps_bl_1 subset: ",
               nrow(df_new), " rows (removed ", n_before - nrow(df_new), ")"))
}

print(paste0("Rows after subsetting: ", nrow(df_new)))

# -----------------------------------------------------------------------
# Complete cases, then normalization.  ORDER IS THE POINT OF THIS BLOCK.
#
# brms drops incomplete cases itself, but only once brm() is called — which is
# after this script would have normalized.  Dropping them here instead makes the
# normalization sample and the estimation sample the same set of rows, so every
# _normalized column is at mean 0 / sd 0.5 on exactly the rows that enter the
# likelihood.  That is what "+1 raw SD" in the counterfactual output means, and
# before 2026-08-22 it silently meant +1 SD of a larger sample.
#
# Model variables = the DV (args[3]) plus every term on the formula RHS
# (args[5], which already contains the focal predictor as well as the
# covariates).  model_formula_vars() unwraps mo() and splits interactions.
# -----------------------------------------------------------------------
model_vars <- c(args[3], model_formula_vars(args[5]))
print(paste0("Model variables for complete-case restriction: ",
             paste(sort(unique(model_vars)), collapse = ", ")))
df_new <- drop_incomplete_model_rows(df_new, model_vars)

print("Normalizing (Gelman 2SD) on the analysis sample...")
df_new <- gelman_normalize_df(
  df_new,
  normalize_in_place     = normalize_in_place_vars,
  ensure_normalized_copy = ensure_normalized_copy_vars,
  need_non_normalized    = need_non_normalized_vars,
  inplace_normalized     = inplace_normalized_vars,
  categorical            = binary_factor_vars,
  monotonic              = monotonic_covariate_vars,
  skip_vars              = gelman_skip_vars
)
verify_gelman_normalization(
  df_new,
  need_non_normalized = need_non_normalized_vars,
  inplace_normalized  = inplace_normalized_vars
)
print(paste0("Rows after complete-case restriction and normalization: ", nrow(df_new)))

# -----------------------------------------------------------------------
# Factor covariates — sourced from categorical_factor_vars.R, which is
# auto-generated by generate_hpc_jobs.py from modules/master_config.py.
# To add or remove a variable, edit CATEGORICAL_FACTOR_VARS in master_config.py
# and re-run generate_hpc_jobs.py.  Do NOT edit the list here directly.
#
# `script_dir` is defined near the top of this section, where gelman_normalization.R
# and normalization_vars.R are sourced.
# -----------------------------------------------------------------------
# `binary_factor_vars` is already loaded — categorical_factor_vars.R is sourced
# in the block above, because gelman_normalize_df() needs the same list to know
# which variables to exclude from normalization.

alerts <- character(0)

for (v in binary_factor_vars) {
  if (v %in% names(df_new)) {
    # Keep sex_v2 in its original coding (1/2), but collapse inhalants 2 -> 0.
    if (v == "inhalants_lifetime") {
      x <- suppressWarnings(as.numeric(as.character(df_new[[v]])))
      x[!is.na(x) & x == 2] <- 0
      df_new[[v]] <- x
      print("  [binary prep] inhalants_lifetime recoded: 2 -> 0")
    }

    df_new[[v]] <- as.factor(df_new[[v]])

    lvl_counts <- table(df_new[[v]], useNA = "no")
    n_lvls <- nlevels(df_new[[v]])
    counts_str <- paste(names(lvl_counts), as.integer(lvl_counts), sep = ":", collapse = ", ")
    print(paste0("  [binary prep] ", v, " levels=", n_lvls, " counts={", counts_str, "}"))

    if (n_lvls != 2) {
      alerts <- c(alerts, paste0(v, " has ", n_lvls, " levels (expected 2)."))
    }
    if (length(lvl_counts) > 0 && any(lvl_counts < 30)) {
      small <- paste(names(lvl_counts)[lvl_counts < 30], as.integer(lvl_counts[lvl_counts < 30]), sep = ":", collapse = ", ")
      alerts <- c(alerts, paste0(v, " has level count(s) < 30 -> ", small))
    }
  }
}

print(paste0(
  "Binary covariates converted to factor when present: ",
  paste(binary_factor_vars, collapse = ", ")
))

if (length(alerts) > 0) {
  print("ALERT: Binary covariate level checks flagged issues:")
  for (a in unique(alerts)) print(paste0("  - ", a))
} else {
  print("Binary covariate level checks passed: each present variable has 2 levels and >=30 observations per level.")
}

# -----------------------------------------------------------------------
# Ordered factor conversion for monotonic (mo()) covariates.
# Variables listed in monotonic_covariates_vars.R appear in brms formulas
# wrapped in mo() and must be integer-coded ordered factors at fit time.
# The file is auto-generated by generate_hpc_jobs.py from
# MONOTONIC_COVARIATES in modules/master_config.py — do not edit manually.
# -----------------------------------------------------------------------
# `monotonic_covariate_vars` is already loaded in the block above, where
# gelman_normalize_df() needs it to exclude mo() covariates from normalization.

for (v in monotonic_covariate_vars) {
  if (v %in% names(df_new)) {
    df_new[[v]] <- as.ordered(as.integer(df_new[[v]]))
    print(paste0(
      "  [ordinal prep] ", v, " -> ordered factor, levels: ",
      paste(levels(df_new[[v]]), collapse = ", ")
    ))
  }
}

print("Lets DO THIS THING!")
brms_master(
  settings = args[1],
  dataframe = df_new,
  dv = args[3],
  iter = as.numeric(args[4]),
  sp_and_covs = args[5],
  covs = args[2],
  spvar = args[6],
  factororno = args[8],
  # args[10] is optional; absent (NA) -> the 0.98 default in the signature.
  adapt_delta = if (length(args) >= 10 && !is.na(args[10]) && nzchar(args[10]))
                  as.numeric(args[10]) else 0.98
)

print("FINISHED")
print(args[3])
print(args[2])
print(args[1])
