### param_recovery_vch.jl  ─  VCH HGF Parameter Recovery (HPC)
###
### For each (record_id, model_type, iteration), this script:
###   1. Loads the participant's empirical VCH stimulus sequence from the
###      already-staged CSV at data_n_cmnds/{project}/{tp}/vch_data/{id}.csv
###      (transferred to HPC by hgf_pipeline.py — no re-staging required)
###   2. Creates an HGF agent and sets the GENERATIVE parameters passed as
###      CLI args (the participant's own fitted posterior medians from the
###      main analysis, i.e. vch_nu / vch_beta / vch_omega [/ vch_omega3])
###   3. Simulates synthetic binary responses via a manual forward pass,
###      identical in structure to the state-extraction pass in
###      model_fitting_singleagent_forarray.jl but sampling each action
###      from the Bernoulli distribution rather than using the observed response
###   4. Fits the HGF to those synthetic responses using the same priors and
###      MCMC settings as the main analysis (MAP init, MCMCSerial, 1000 samples)
###   5. Saves per-run outputs to param_recovery/results/{model_type}/:
###        {record_id}_iter{i}.jls          full chains (Julia Serialization)
###        {record_id}_iter{i}.csv          full chains as CSV (Python-readable)
###        {record_id}_iter{i}_medians.csv  recovered posterior medians
###        {record_id}_iter{i}_rhats.csv    Gelman-Rubin diagnostics
###
### Columns in _medians.csv:
###   record_id, iteration,
###   action_precision, prior_posterior_weight, xprob_volatility [, xvol_volatility]
###
### Columns in _rhats.csv:
###   action_precision.session[1], prior_posterior_weight.session[1],
###   xprob_volatility.session[1] [, xvol_volatility.session[1]], record_id, iteration
###
### Columns in chains .csv match main-analysis chains exactly:
###   iteration, chain,
###   action_precision.session[1], prior_posterior_weight.session[1],
###   xprob_volatility.session[1] [, xvol_volatility.session[1]], lp, ...
###
### Run via dSQ job array generated by param_recovery_vch.py.
###
### Usage:
###   julia --project=. --threads 4 param_recovery_vch.jl \
###         <record_id> <model_type> <iteration> <nu> <beta> <omega> [<omega3>]
###
###   record_id   — Participant record ID (integer)
###   model_type  — "2level_empiric" or "3level_empiric"
###   iteration   — Recovery iteration index (1–N_ITERATIONS)
###   nu          — Generative prior_posterior_weight (df col: vch_nu / vch_nu_3lev)
###   beta        — Generative action_precision       (df col: vch_beta / vch_beta_3lev)
###   omega       — Generative xprob_volatility       (df col: vch_omega / vch_omega_3lev)
###   omega3      — Generative xvol_volatility (3-level only; df col: vch_omega3_3lev)
###   n_samples   — Optional: MCMC samples per chain (default 1000; use e.g. 50 for smoke tests)

################################################################################
# ─── ROLE IN THE MANUSCRIPT ───────────────────────────────────────────────────
#
# POSTERIOR-BASED RECOVERY, part 1 of 2.  Produces Supplementary Fig. S3d and S3e.
#
#     THIS SCRIPT (HPC, one task per participant × iteration)
#         ──▶ param_recovery_vch.py (compile + plot)
#
# How this differs from the PRIOR-based recovery
#     Prior-based recovery asks whether the model is identifiable anywhere in its
#     prior volume.  This asks the narrower and more directly relevant question:
#     are the parameters recoverable in the region of parameter space where THIS
#     SAMPLE actually sits, given THESE participants' real stimulus sequences?
#
#     Accordingly, the generative parameters are not sampled — they are each
#     participant's own fitted posterior medians from the main analysis, and the
#     stimulus sequence is that participant's real one, reused from the staging
#     CSVs.  Ten synthetic response sequences are generated per participant and
#     each is refit under the main analysis's exact priors and MCMC settings.
#
# Reported in the manuscript
#     r = 0.936 (nu), 0.832 (beta), 0.764 (omega) between generative and recovered
#     medians.  Parameter identifiability was also checked off-diagonal: the
#     largest cross-parameter correlation was generative nu vs recovered omega
#     (r = 0.43), with nu and beta essentially uncorrelated.
################################################################################

using ActionModels, HierarchicalGaussianFiltering
using CSV, Serialization
using Turing
using DataFrames
using MCMCChains
using Distributions
using Statistics: median

include("helper_functions/create_agent.jl")

################################################################################
# ─── PARSE ARGUMENTS ──────────────────────────────────────────────────────────
################################################################################

if length(ARGS) < 6
    error(
        "Usage: julia param_recovery_vch.jl " *
        "<record_id> <model_type> <iteration> <nu> <beta> <omega> [<omega3>] [<n_samples>]"
    )
end

record_id  = parse(Int,     ARGS[1])
model_type = ARGS[2]           # "2level_empiric" or "3level_empiric"
iteration  = parse(Int,     ARGS[3])
gen_nu     = parse(Float64, ARGS[4])   # prior_posterior_weight
gen_beta   = parse(Float64, ARGS[5])   # action_precision
gen_omega  = parse(Float64, ARGS[6])   # xprob_volatility

gen_omega3 = NaN  # xvol_volatility — only used for 3-level

if model_type == "3level_empiric"
    if length(ARGS) < 7
        error("3-level model requires omega3 as the 7th argument " *
              "(df col: vch_omega3_3lev / xvol_volatility)")
    end
    gen_omega3 = parse(Float64, ARGS[7])
    # optional n_samples override is arg 8 for 3-level
    n_samples_override = length(ARGS) >= 8 ? parse(Int, ARGS[8]) : nothing
elseif model_type == "2level_empiric"
    # optional n_samples override is arg 7 for 2-level
    n_samples_override = length(ARGS) >= 7 ? parse(Int, ARGS[7]) : nothing
else
    error("model_type must be \"2level_empiric\" or \"3level_empiric\", got: \"$model_type\"")
end

################################################################################
# ─── SETTINGS (match main-analysis model_fitting_singleagent_forarray.jl) ─────
################################################################################

const PROJECT   = "hppd_manuscript"
const TIMEPOINT = "hppd"
const MODALITY  = "vch"
const N_SAMPLES = isnothing(n_samples_override) ? 1000 : n_samples_override
const N_CHAINS  = 4

use_optim  = true
my_sampler = NUTS(adtype=AutoForwardDiff())

################################################################################
# ─── PATHS AND SKIP CHECK ─────────────────────────────────────────────────────
################################################################################

out_dir      = joinpath("param_recovery", "results", model_type)
mkpath(out_dir)
out_stem     = joinpath(out_dir, "$(record_id)_iter$(iteration)")
chains_jls   = "$(out_stem).jls"
medians_file = "$(out_stem)_medians.csv"

println("=" ^ 60)
println("VCH Param Recovery")
println("  record_id  = $record_id")
println("  model_type = $model_type")
println("  iteration  = $iteration")
println("Generative parameters:")
println("  nu    (prior_posterior_weight) = $gen_nu")
println("  beta  (action_precision)       = $gen_beta")
println("  omega (xprob_volatility)       = $gen_omega")
if model_type == "3level_empiric"
    println("  omega3 (xvol_volatility)       = $gen_omega3")
end
println("=" ^ 60)

if isfile(chains_jls) && isfile(medians_file)
    println("Already complete — skipping ($(basename(chains_jls)) + medians found).")
    exit(0)
end

################################################################################
# ─── LOAD STIMULUS SEQUENCE ───────────────────────────────────────────────────
# Reads the per-participant CSV staged by hgf_pipeline.py (step 2).
# Required columns: empirical_condition, response, condition, subj_id
################################################################################

stim_path = joinpath(
    "data_n_cmnds", PROJECT, TIMEPOINT, "$(MODALITY)_data", "$(record_id).csv"
)
if !isfile(stim_path)
    error(
        "Stimulus CSV not found: $stim_path\n" *
        "Have the VCH staging CSVs been transferred to HPC from 02_hgf_modeling/data_n_cmnds/?"
    )
end

stim_df              = CSV.read(stim_path, DataFrame)
empirical_conditions = collect(Float64, stim_df[!, :empirical_condition])
println("Loaded $(length(empirical_conditions)) trials from $(basename(stim_path))")

################################################################################
# ─── PHASE 1: SIMULATE SYNTHETIC RESPONSES ────────────────────────────────────
#
# Manual forward pass — mirrors the state-extraction loop in
# model_fitting_singleagent_forarray.jl, but SAMPLES each binary action
# from the agent's Bernoulli distribution instead of using the observed response.
#
# This structure is used (rather than simulate!) because the VCH action model
# routes the previous action back as HGF input:
#   hgf_input = load_actions(model_attributes).action
#   update_hgf!(hgf, hgf_input)
# The manual loop with set_actions! ensures this recurrence is handled correctly
# regardless of ActionModels version internals.
################################################################################

hgf_string = model_type == "3level_empiric" ? "binary_3level" : "binary_2level"
am_sim     = create_agent(hgf_string)
agent_sim  = init_agent(am_sim)   # no save_history needed for simulation

gen_params = if model_type == "3level_empiric"
    (;
        prior_posterior_weight = gen_nu,
        action_precision       = gen_beta,
        xprob_volatility       = gen_omega,
        xvol_volatility        = gen_omega3,
    )
else
    (;
        prior_posterior_weight = gen_nu,
        action_precision       = gen_beta,
        xprob_volatility       = gen_omega,
    )
end

set_parameters!(agent_sim, gen_params)
reset!(agent_sim)

simulated_responses = Float64[]
for input in empirical_conditions
    dist   = agent_sim.action_model(agent_sim.model_attributes, input)
    action = Float64(rand(dist))   # sample from Bernoulli, not observe
    push!(simulated_responses, action)
    set_actions!(agent_sim, :action, action)   # store for next trial's HGF update
end

n_detect = Int(sum(simulated_responses))
println(
    "Simulated $(length(simulated_responses)) responses: " *
    "$n_detect detections, $(length(simulated_responses) - n_detect) misses"
)

################################################################################
# ─── PHASE 2: FIT HGF TO SIMULATED RESPONSES ─────────────────────────────────
#
# Priors are identical to model_fitting_singleagent_forarray.jl so that the
# recovery is subject to the same constraints as the original estimation.
################################################################################

am_fit = create_agent(hgf_string)

priors = if model_type == "2level_empiric"
    (;
        action_precision       = truncated(Normal(0.29350739^(-1), 1), lower = 0.001),
        prior_posterior_weight = truncated(Normal(0.72646851, 1),      lower = 0),
        xprob_volatility       = truncated(Normal(-5.1682685, 1),      upper = -0.5),
    )
else  # "3level_empiric"
    (;
        action_precision       = truncated(Normal(0.29350739^(-1), 1), lower = 0.001),
        prior_posterior_weight = truncated(Normal(0.72646851, 1),      lower = 0),
        xprob_volatility       = truncated(Normal(-5.1682685, 1),      upper = -0.5),
        xvol_volatility        = truncated(Normal(-6, 1),              upper = -0.5),
    )
end

model_fit = create_model(
    am_fit,
    priors,
    empirical_conditions,
    simulated_responses,
    check_parameter_rejections = true,
    verbose = false,
)

println("Sampling posterior ($N_SAMPLES samples × $N_CHAINS chains, MAP init)...")
result = sample_posterior!(model_fit, MCMCSerial();
    sampler     = my_sampler,
    init_params = :MAP,
    n_samples   = N_SAMPLES,
    n_chains    = N_CHAINS,
    progress    = true,
)

################################################################################
# ─── SAVE OUTPUTS ─────────────────────────────────────────────────────────────
################################################################################

# ── Full chains: .jls (compact Julia-native) + .csv (Python-readable) ─────────
serialize(chains_jls, result)
CSV.write("$(out_stem).csv", DataFrame(result))
println("Chains saved: $(out_stem).jls  +  $(out_stem).csv")

# ── R-hats ─────────────────────────────────────────────────────────────────────
# Column names match main-analysis _rhats.csv: "param.session[1]"
rhats_raw            = DataFrame(rhat(result))
df_rhats             = unstack(rhats_raw, :parameters, :rhat)
df_rhats[!, :record_id] .= record_id
df_rhats[!, :iteration] .= iteration
CSV.write("$(out_stem)_rhats.csv", df_rhats)
println("Rhats saved: $(out_stem)_rhats.csv")

# ── Recovered parameter medians ────────────────────────────────────────────────
# Column names match main-analysis _medians.csv:
#   action_precision, prior_posterior_weight, xprob_volatility [, xvol_volatility]
# Plus record_id and iteration for traceability.
param_names         = keys(priors)
param_names_strings = [string(n) for n in param_names]
session_params      = get_session_parameters!(model_fit)
session_id_sym      = Symbol(session_params.session_ids[1])
medians_vec         = [
    median(session_params.value[pn][session_id_sym]) for pn in param_names
]

row = (;
    record_id = record_id,
    iteration = iteration,
    [Symbol(n) => m for (n, m) in zip(param_names_strings, medians_vec)]...
)
CSV.write(medians_file, DataFrame([row]))
println("Medians saved: $medians_file")

println("Done — record_id=$record_id, $model_type, iteration=$iteration")
